/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ManagementorganizationsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ManagementorganizationsApiTests
    {
        private ManagementorganizationsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ManagementorganizationsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ManagementorganizationsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ManagementorganizationsApi
            //Assert.IsInstanceOfType(typeof(ManagementorganizationsApi), instance, "instance is a ManagementorganizationsApi");
        }

        /// <summary>
        /// Test CreateAnOrganizationV3ManagementOrganizationsPost
        /// </summary>
        [Test]
        public void CreateAnOrganizationV3ManagementOrganizationsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateOrganizationRequestModel body = null;
            //var response = instance.CreateAnOrganizationV3ManagementOrganizationsPost(body);
            //Assert.IsInstanceOf<CreateOrganizationResponseModel> (response, "response is CreateOrganizationResponseModel");
        }
        /// <summary>
        /// Test DeleteAnOrganizationV3ManagementOrganizationsOrganizationIdDelete
        /// </summary>
        [Test]
        public void DeleteAnOrganizationV3ManagementOrganizationsOrganizationIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object organizationId = null;
            //var response = instance.DeleteAnOrganizationV3ManagementOrganizationsOrganizationIdDelete(organizationId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetAnOrganizationV3ManagementOrganizationsOrganizationIdGet
        /// </summary>
        [Test]
        public void GetAnOrganizationV3ManagementOrganizationsOrganizationIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object organizationId = null;
            //var response = instance.GetAnOrganizationV3ManagementOrganizationsOrganizationIdGet(organizationId);
            //Assert.IsInstanceOf<GetOrganizationResponseModel> (response, "response is GetOrganizationResponseModel");
        }
        /// <summary>
        /// Test ListAllOrganizationsV3ManagementOrganizationsGet
        /// </summary>
        [Test]
        public void ListAllOrganizationsV3ManagementOrganizationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListAllOrganizationsV3ManagementOrganizationsGet();
            //Assert.IsInstanceOf<ListOrganizationsResponseModel> (response, "response is ListOrganizationsResponseModel");
        }
        /// <summary>
        /// Test ListOrganizationApplicationsV3ManagementOrganizationsOrganizationIdApplicationsGet
        /// </summary>
        [Test]
        public void ListOrganizationApplicationsV3ManagementOrganizationsOrganizationIdApplicationsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object organizationId = null;
            //var response = instance.ListOrganizationApplicationsV3ManagementOrganizationsOrganizationIdApplicationsGet(organizationId);
            //Assert.IsInstanceOf<ListOrganizationApplicationsResponseModel> (response, "response is ListOrganizationApplicationsResponseModel");
        }
        /// <summary>
        /// Test UpdateAnOrganizationV3ManagementOrganizationsOrganizationIdPatch
        /// </summary>
        [Test]
        public void UpdateAnOrganizationV3ManagementOrganizationsOrganizationIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateOrganizationRequestModel body = null;
            //Object organizationId = null;
            //var response = instance.UpdateAnOrganizationV3ManagementOrganizationsOrganizationIdPatch(body, organizationId);
            //Assert.IsInstanceOf<UpdateOrganizationResponseModel> (response, "response is UpdateOrganizationResponseModel");
        }
    }

}
