/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelsllmsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ModelsllmsApiTests
    {
        private ModelsllmsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ModelsllmsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelsllmsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ModelsllmsApi
            //Assert.IsInstanceOfType(typeof(ModelsllmsApi), instance, "instance is a ModelsllmsApi");
        }

        /// <summary>
        /// Test CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost
        /// </summary>
        [Test]
        public void CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateLLMCompletionRequestModel body = null;
            //LLMInferenceProviderID llmInferenceProviderId = null;
            //LLMModelID llmModelId = null;
            //var response = instance.CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost(body, llmInferenceProviderId, llmModelId);
            //Assert.IsInstanceOf<CreateLLMCompletionResponseModel> (response, "response is CreateLLMCompletionResponseModel");
        }
        /// <summary>
        /// Test CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost
        /// </summary>
        [Test]
        public void CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateLLMCompletionRequestModel body = null;
            //LLMInferenceProviderID llmInferenceProviderId = null;
            //LLMModelID llmModelId = null;
            //var response = instance.CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost(body, llmInferenceProviderId, llmModelId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet
        /// </summary>
        [Test]
        public void GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LLMInferenceProviderID llmInferenceProviderId = null;
            //LLMModelID llmModelId = null;
            //var response = instance.GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet(llmInferenceProviderId, llmModelId);
            //Assert.IsInstanceOf<GetLLMModelResponseModel> (response, "response is GetLLMModelResponseModel");
        }
        /// <summary>
        /// Test ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet
        /// </summary>
        [Test]
        public void ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet();
            //Assert.IsInstanceOf<ListLLMInferenceProvidersResponseModel> (response, "response is ListLLMInferenceProvidersResponseModel");
        }
        /// <summary>
        /// Test ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet
        /// </summary>
        [Test]
        public void ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //LLMInferenceProviderID llmInferenceProviderId = null;
            //var response = instance.ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet(llmInferenceProviderId);
            //Assert.IsInstanceOf<ListLLMInferenceProviderModelsResponseModel> (response, "response is ListLLMInferenceProviderModelsResponseModel");
        }
    }

}
