/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RagApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RagApiTests
    {
        private RagApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RagApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RagApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RagApi
            //Assert.IsInstanceOfType(typeof(RagApi), instance, "instance is a RagApi");
        }

        /// <summary>
        /// Test CreateACorpusV3RagCorporaPost
        /// </summary>
        [Test]
        public void CreateACorpusV3RagCorporaPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateCorpusRequestModel body = null;
            //var response = instance.CreateACorpusV3RagCorporaPost(body);
            //Assert.IsInstanceOf<CreateCorpusResponseModel> (response, "response is CreateCorpusResponseModel");
        }
        /// <summary>
        /// Test CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost
        /// </summary>
        [Test]
        public void CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateReferenceObjectSearchRequestModel body = null;
            //Object corpusId = null;
            //var response = instance.CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost(body, corpusId);
            //Assert.IsInstanceOf<CreateReferenceObjectSearchResponseModel> (response, "response is CreateReferenceObjectSearchResponseModel");
        }
        /// <summary>
        /// Test CreatesAReferenceObjectV3RagReferenceObjectsPost
        /// </summary>
        [Test]
        public void CreatesAReferenceObjectV3RagReferenceObjectsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object uploadFile = null;
            //Object corpusId = null;
            //var response = instance.CreatesAReferenceObjectV3RagReferenceObjectsPost(uploadFile, corpusId);
            //Assert.IsInstanceOf<CreateReferenceObjectResponseModel> (response, "response is CreateReferenceObjectResponseModel");
        }
        /// <summary>
        /// Test DeleteACorpusV3RagCorporaCorpusIdDelete
        /// </summary>
        [Test]
        public void DeleteACorpusV3RagCorporaCorpusIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object corpusId = null;
            //var response = instance.DeleteACorpusV3RagCorporaCorpusIdDelete(corpusId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test DeletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDelete
        /// </summary>
        [Test]
        public void DeletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object referenceObjectId = null;
            //var response = instance.DeletesAReferenceObjectV3RagReferenceObjectsReferenceObjectIdDelete(referenceObjectId);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        /// <summary>
        /// Test GetACorpusV3RagCorporaCorpusIdGet
        /// </summary>
        [Test]
        public void GetACorpusV3RagCorporaCorpusIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object corpusId = null;
            //var response = instance.GetACorpusV3RagCorporaCorpusIdGet(corpusId);
            //Assert.IsInstanceOf<GetCorpusResponseModel> (response, "response is GetCorpusResponseModel");
        }
        /// <summary>
        /// Test GetAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGet
        /// </summary>
        [Test]
        public void GetAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object referenceObjectId = null;
            //var response = instance.GetAReferenceObjectV3RagReferenceObjectsReferenceObjectIdGet(referenceObjectId);
            //Assert.IsInstanceOf<GetReferenceObjectResponseModel> (response, "response is GetReferenceObjectResponseModel");
        }
        /// <summary>
        /// Test ListAllCorporaV3RagCorporaGet
        /// </summary>
        [Test]
        public void ListAllCorporaV3RagCorporaGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListAllCorporaV3RagCorporaGet();
            //Assert.IsInstanceOf<ListCorporaResponseModel> (response, "response is ListCorporaResponseModel");
        }
        /// <summary>
        /// Test ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet
        /// </summary>
        [Test]
        public void ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object corpusId = null;
            //var response = instance.ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet(corpusId);
            //Assert.IsInstanceOf<ListCorpusReferenceObjectsResponseModel> (response, "response is ListCorpusReferenceObjectsResponseModel");
        }
        /// <summary>
        /// Test ListsAllReferenceObjectsV3RagReferenceObjectsGet
        /// </summary>
        [Test]
        public void ListsAllReferenceObjectsV3RagReferenceObjectsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListsAllReferenceObjectsV3RagReferenceObjectsGet();
            //Assert.IsInstanceOf<ListReferenceObjectsResponseModel> (response, "response is ListReferenceObjectsResponseModel");
        }
        /// <summary>
        /// Test UpdateACorpusV3RagCorporaCorpusIdPatch
        /// </summary>
        [Test]
        public void UpdateACorpusV3RagCorporaCorpusIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateCorpusRequestModel body = null;
            //Object corpusId = null;
            //var response = instance.UpdateACorpusV3RagCorporaCorpusIdPatch(body, corpusId);
            //Assert.IsInstanceOf<UpdateCorpusResponseModel> (response, "response is UpdateCorpusResponseModel");
        }
    }

}
