/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ApplicationDataModel
    /// </summary>
    [DataContract]
        public partial class ApplicationDataModel :  IEquatable<ApplicationDataModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationDataModel" /> class.
        /// </summary>
        /// <param name="id">ID of this application..</param>
        /// <param name="name">The name of this application. (required).</param>
        /// <param name="organizationId">The UUID of the organization behind this application. (required).</param>
        /// <param name="apiCallsLimitPerMonth">The maximum amount of API calls this application can make in a month. (default to 0).</param>
        /// <param name="llmTokensLimitPerMonth">The maximum amount of LLM tokens (combined I/O) this application can use in a month. (default to 0).</param>
        /// <param name="embeddingTokensLimitPerMonth">The maximum amount of embedding tokens this application can use in a month. (default to 0).</param>
        /// <param name="imageGenerationLimitPerMonth">The maximum amount of images this application can generate in a month. (default to 0).</param>
        /// <param name="allowLlmQueries">Should this application be allowed to make queries to LLMs? (default to true).</param>
        /// <param name="allowCorpusCreation">Should this application be allowed to create corpuses? (default to true).</param>
        /// <param name="allowImageGeneration">Should this application be allowed to create images? (default to true).</param>
        /// <param name="allowExpensiveQueries">Should this application be allowed to make potentially expensive queries? (default to true).</param>
        /// <param name="accessKey">The access key for using this application..</param>
        /// <param name="webhookUrl">Webhook URL to use when notifying of queued events..</param>
        /// <param name="webhookAuthorizationKey">Webhook authorization key to use in order to verify the origin of webhook events..</param>
        /// <param name="isActive">Is this application active? (default to true).</param>
        /// <param name="isAuthoritative">Is this application allowed to access management endpoints? NOTE: Usable for deployment owners only. (default to false).</param>
        /// <param name="createdAt">Application creation date..</param>
        public ApplicationDataModel(Object id = default(Object), Object name = default(Object), Object organizationId = default(Object), Object apiCallsLimitPerMonth = 0, Object llmTokensLimitPerMonth = 0, Object embeddingTokensLimitPerMonth = 0, Object imageGenerationLimitPerMonth = 0, Object allowLlmQueries = true, Object allowCorpusCreation = true, Object allowImageGeneration = true, Object allowExpensiveQueries = true, Object accessKey = default(Object), Object webhookUrl = default(Object), Object webhookAuthorizationKey = default(Object), Object isActive = true, Object isAuthoritative = false, Object createdAt = default(Object))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for ApplicationDataModel and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "organizationId" is required (not null)
            if (organizationId == null)
            {
                throw new InvalidDataException("organizationId is a required property for ApplicationDataModel and cannot be null");
            }
            else
            {
                this.OrganizationId = organizationId;
            }
            this.Id = id;
            // use default value if no "apiCallsLimitPerMonth" provided
            if (apiCallsLimitPerMonth == null)
            {
                this.ApiCallsLimitPerMonth = 0;
            }
            else
            {
                this.ApiCallsLimitPerMonth = apiCallsLimitPerMonth;
            }
            // use default value if no "llmTokensLimitPerMonth" provided
            if (llmTokensLimitPerMonth == null)
            {
                this.LlmTokensLimitPerMonth = 0;
            }
            else
            {
                this.LlmTokensLimitPerMonth = llmTokensLimitPerMonth;
            }
            // use default value if no "embeddingTokensLimitPerMonth" provided
            if (embeddingTokensLimitPerMonth == null)
            {
                this.EmbeddingTokensLimitPerMonth = 0;
            }
            else
            {
                this.EmbeddingTokensLimitPerMonth = embeddingTokensLimitPerMonth;
            }
            // use default value if no "imageGenerationLimitPerMonth" provided
            if (imageGenerationLimitPerMonth == null)
            {
                this.ImageGenerationLimitPerMonth = 0;
            }
            else
            {
                this.ImageGenerationLimitPerMonth = imageGenerationLimitPerMonth;
            }
            // use default value if no "allowLlmQueries" provided
            if (allowLlmQueries == null)
            {
                this.AllowLlmQueries = true;
            }
            else
            {
                this.AllowLlmQueries = allowLlmQueries;
            }
            // use default value if no "allowCorpusCreation" provided
            if (allowCorpusCreation == null)
            {
                this.AllowCorpusCreation = true;
            }
            else
            {
                this.AllowCorpusCreation = allowCorpusCreation;
            }
            // use default value if no "allowImageGeneration" provided
            if (allowImageGeneration == null)
            {
                this.AllowImageGeneration = true;
            }
            else
            {
                this.AllowImageGeneration = allowImageGeneration;
            }
            // use default value if no "allowExpensiveQueries" provided
            if (allowExpensiveQueries == null)
            {
                this.AllowExpensiveQueries = true;
            }
            else
            {
                this.AllowExpensiveQueries = allowExpensiveQueries;
            }
            this.AccessKey = accessKey;
            this.WebhookUrl = webhookUrl;
            this.WebhookAuthorizationKey = webhookAuthorizationKey;
            // use default value if no "isActive" provided
            if (isActive == null)
            {
                this.IsActive = true;
            }
            else
            {
                this.IsActive = isActive;
            }
            // use default value if no "isAuthoritative" provided
            if (isAuthoritative == null)
            {
                this.IsAuthoritative = false;
            }
            else
            {
                this.IsAuthoritative = isAuthoritative;
            }
            this.CreatedAt = createdAt;
        }
        
        /// <summary>
        /// ID of this application.
        /// </summary>
        /// <value>ID of this application.</value>
        [DataMember(Name="_id", EmitDefaultValue=false)]
        public Object Id { get; set; }

        /// <summary>
        /// The name of this application.
        /// </summary>
        /// <value>The name of this application.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public Object Name { get; set; }

        /// <summary>
        /// The UUID of the organization behind this application.
        /// </summary>
        /// <value>The UUID of the organization behind this application.</value>
        [DataMember(Name="organization_id", EmitDefaultValue=false)]
        public Object OrganizationId { get; set; }

        /// <summary>
        /// The maximum amount of API calls this application can make in a month.
        /// </summary>
        /// <value>The maximum amount of API calls this application can make in a month.</value>
        [DataMember(Name="api_calls_limit_per_month", EmitDefaultValue=false)]
        public Object ApiCallsLimitPerMonth { get; set; }

        /// <summary>
        /// The maximum amount of LLM tokens (combined I/O) this application can use in a month.
        /// </summary>
        /// <value>The maximum amount of LLM tokens (combined I/O) this application can use in a month.</value>
        [DataMember(Name="llm_tokens_limit_per_month", EmitDefaultValue=false)]
        public Object LlmTokensLimitPerMonth { get; set; }

        /// <summary>
        /// The maximum amount of embedding tokens this application can use in a month.
        /// </summary>
        /// <value>The maximum amount of embedding tokens this application can use in a month.</value>
        [DataMember(Name="embedding_tokens_limit_per_month", EmitDefaultValue=false)]
        public Object EmbeddingTokensLimitPerMonth { get; set; }

        /// <summary>
        /// The maximum amount of images this application can generate in a month.
        /// </summary>
        /// <value>The maximum amount of images this application can generate in a month.</value>
        [DataMember(Name="image_generation_limit_per_month", EmitDefaultValue=false)]
        public Object ImageGenerationLimitPerMonth { get; set; }

        /// <summary>
        /// Should this application be allowed to make queries to LLMs?
        /// </summary>
        /// <value>Should this application be allowed to make queries to LLMs?</value>
        [DataMember(Name="allow_llm_queries", EmitDefaultValue=false)]
        public Object AllowLlmQueries { get; set; }

        /// <summary>
        /// Should this application be allowed to create corpuses?
        /// </summary>
        /// <value>Should this application be allowed to create corpuses?</value>
        [DataMember(Name="allow_corpus_creation", EmitDefaultValue=false)]
        public Object AllowCorpusCreation { get; set; }

        /// <summary>
        /// Should this application be allowed to create images?
        /// </summary>
        /// <value>Should this application be allowed to create images?</value>
        [DataMember(Name="allow_image_generation", EmitDefaultValue=false)]
        public Object AllowImageGeneration { get; set; }

        /// <summary>
        /// Should this application be allowed to make potentially expensive queries?
        /// </summary>
        /// <value>Should this application be allowed to make potentially expensive queries?</value>
        [DataMember(Name="allow_expensive_queries", EmitDefaultValue=false)]
        public Object AllowExpensiveQueries { get; set; }

        /// <summary>
        /// The access key for using this application.
        /// </summary>
        /// <value>The access key for using this application.</value>
        [DataMember(Name="access_key", EmitDefaultValue=false)]
        public Object AccessKey { get; set; }

        /// <summary>
        /// Webhook URL to use when notifying of queued events.
        /// </summary>
        /// <value>Webhook URL to use when notifying of queued events.</value>
        [DataMember(Name="webhook_url", EmitDefaultValue=false)]
        public Object WebhookUrl { get; set; }

        /// <summary>
        /// Webhook authorization key to use in order to verify the origin of webhook events.
        /// </summary>
        /// <value>Webhook authorization key to use in order to verify the origin of webhook events.</value>
        [DataMember(Name="webhook_authorization_key", EmitDefaultValue=false)]
        public Object WebhookAuthorizationKey { get; set; }

        /// <summary>
        /// Is this application active?
        /// </summary>
        /// <value>Is this application active?</value>
        [DataMember(Name="is_active", EmitDefaultValue=false)]
        public Object IsActive { get; set; }

        /// <summary>
        /// Is this application allowed to access management endpoints? NOTE: Usable for deployment owners only.
        /// </summary>
        /// <value>Is this application allowed to access management endpoints? NOTE: Usable for deployment owners only.</value>
        [DataMember(Name="is_authoritative", EmitDefaultValue=false)]
        public Object IsAuthoritative { get; set; }

        /// <summary>
        /// Application creation date.
        /// </summary>
        /// <value>Application creation date.</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public Object CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApplicationDataModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  ApiCallsLimitPerMonth: ").Append(ApiCallsLimitPerMonth).Append("\n");
            sb.Append("  LlmTokensLimitPerMonth: ").Append(LlmTokensLimitPerMonth).Append("\n");
            sb.Append("  EmbeddingTokensLimitPerMonth: ").Append(EmbeddingTokensLimitPerMonth).Append("\n");
            sb.Append("  ImageGenerationLimitPerMonth: ").Append(ImageGenerationLimitPerMonth).Append("\n");
            sb.Append("  AllowLlmQueries: ").Append(AllowLlmQueries).Append("\n");
            sb.Append("  AllowCorpusCreation: ").Append(AllowCorpusCreation).Append("\n");
            sb.Append("  AllowImageGeneration: ").Append(AllowImageGeneration).Append("\n");
            sb.Append("  AllowExpensiveQueries: ").Append(AllowExpensiveQueries).Append("\n");
            sb.Append("  AccessKey: ").Append(AccessKey).Append("\n");
            sb.Append("  WebhookUrl: ").Append(WebhookUrl).Append("\n");
            sb.Append("  WebhookAuthorizationKey: ").Append(WebhookAuthorizationKey).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsAuthoritative: ").Append(IsAuthoritative).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApplicationDataModel);
        }

        /// <summary>
        /// Returns true if ApplicationDataModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ApplicationDataModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicationDataModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.OrganizationId == input.OrganizationId ||
                    (this.OrganizationId != null &&
                    this.OrganizationId.Equals(input.OrganizationId))
                ) && 
                (
                    this.ApiCallsLimitPerMonth == input.ApiCallsLimitPerMonth ||
                    (this.ApiCallsLimitPerMonth != null &&
                    this.ApiCallsLimitPerMonth.Equals(input.ApiCallsLimitPerMonth))
                ) && 
                (
                    this.LlmTokensLimitPerMonth == input.LlmTokensLimitPerMonth ||
                    (this.LlmTokensLimitPerMonth != null &&
                    this.LlmTokensLimitPerMonth.Equals(input.LlmTokensLimitPerMonth))
                ) && 
                (
                    this.EmbeddingTokensLimitPerMonth == input.EmbeddingTokensLimitPerMonth ||
                    (this.EmbeddingTokensLimitPerMonth != null &&
                    this.EmbeddingTokensLimitPerMonth.Equals(input.EmbeddingTokensLimitPerMonth))
                ) && 
                (
                    this.ImageGenerationLimitPerMonth == input.ImageGenerationLimitPerMonth ||
                    (this.ImageGenerationLimitPerMonth != null &&
                    this.ImageGenerationLimitPerMonth.Equals(input.ImageGenerationLimitPerMonth))
                ) && 
                (
                    this.AllowLlmQueries == input.AllowLlmQueries ||
                    (this.AllowLlmQueries != null &&
                    this.AllowLlmQueries.Equals(input.AllowLlmQueries))
                ) && 
                (
                    this.AllowCorpusCreation == input.AllowCorpusCreation ||
                    (this.AllowCorpusCreation != null &&
                    this.AllowCorpusCreation.Equals(input.AllowCorpusCreation))
                ) && 
                (
                    this.AllowImageGeneration == input.AllowImageGeneration ||
                    (this.AllowImageGeneration != null &&
                    this.AllowImageGeneration.Equals(input.AllowImageGeneration))
                ) && 
                (
                    this.AllowExpensiveQueries == input.AllowExpensiveQueries ||
                    (this.AllowExpensiveQueries != null &&
                    this.AllowExpensiveQueries.Equals(input.AllowExpensiveQueries))
                ) && 
                (
                    this.AccessKey == input.AccessKey ||
                    (this.AccessKey != null &&
                    this.AccessKey.Equals(input.AccessKey))
                ) && 
                (
                    this.WebhookUrl == input.WebhookUrl ||
                    (this.WebhookUrl != null &&
                    this.WebhookUrl.Equals(input.WebhookUrl))
                ) && 
                (
                    this.WebhookAuthorizationKey == input.WebhookAuthorizationKey ||
                    (this.WebhookAuthorizationKey != null &&
                    this.WebhookAuthorizationKey.Equals(input.WebhookAuthorizationKey))
                ) && 
                (
                    this.IsActive == input.IsActive ||
                    (this.IsActive != null &&
                    this.IsActive.Equals(input.IsActive))
                ) && 
                (
                    this.IsAuthoritative == input.IsAuthoritative ||
                    (this.IsAuthoritative != null &&
                    this.IsAuthoritative.Equals(input.IsAuthoritative))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.OrganizationId != null)
                    hashCode = hashCode * 59 + this.OrganizationId.GetHashCode();
                if (this.ApiCallsLimitPerMonth != null)
                    hashCode = hashCode * 59 + this.ApiCallsLimitPerMonth.GetHashCode();
                if (this.LlmTokensLimitPerMonth != null)
                    hashCode = hashCode * 59 + this.LlmTokensLimitPerMonth.GetHashCode();
                if (this.EmbeddingTokensLimitPerMonth != null)
                    hashCode = hashCode * 59 + this.EmbeddingTokensLimitPerMonth.GetHashCode();
                if (this.ImageGenerationLimitPerMonth != null)
                    hashCode = hashCode * 59 + this.ImageGenerationLimitPerMonth.GetHashCode();
                if (this.AllowLlmQueries != null)
                    hashCode = hashCode * 59 + this.AllowLlmQueries.GetHashCode();
                if (this.AllowCorpusCreation != null)
                    hashCode = hashCode * 59 + this.AllowCorpusCreation.GetHashCode();
                if (this.AllowImageGeneration != null)
                    hashCode = hashCode * 59 + this.AllowImageGeneration.GetHashCode();
                if (this.AllowExpensiveQueries != null)
                    hashCode = hashCode * 59 + this.AllowExpensiveQueries.GetHashCode();
                if (this.AccessKey != null)
                    hashCode = hashCode * 59 + this.AccessKey.GetHashCode();
                if (this.WebhookUrl != null)
                    hashCode = hashCode * 59 + this.WebhookUrl.GetHashCode();
                if (this.WebhookAuthorizationKey != null)
                    hashCode = hashCode * 59 + this.WebhookAuthorizationKey.GetHashCode();
                if (this.IsActive != null)
                    hashCode = hashCode * 59 + this.IsActive.GetHashCode();
                if (this.IsAuthoritative != null)
                    hashCode = hashCode * 59 + this.IsAuthoritative.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
