/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ApplicationQueryPipelineTraceDataModel
    /// </summary>
    [DataContract]
        public partial class ApplicationQueryPipelineTraceDataModel :  IEquatable<ApplicationQueryPipelineTraceDataModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicationQueryPipelineTraceDataModel" /> class.
        /// </summary>
        /// <param name="id">The UUID of this usage event..</param>
        /// <param name="applicationId">The UUID of the application associated with this usage event. (required).</param>
        /// <param name="pipelineTraceEvents">pipelineTraceEvents (default to []).</param>
        /// <param name="createdAt">Event creation date..</param>
        public ApplicationQueryPipelineTraceDataModel(Object id = default(Object), Object applicationId = default(Object), Object pipelineTraceEvents = [], Object createdAt = default(Object))
        {
            // to ensure "applicationId" is required (not null)
            if (applicationId == null)
            {
                throw new InvalidDataException("applicationId is a required property for ApplicationQueryPipelineTraceDataModel and cannot be null");
            }
            else
            {
                this.ApplicationId = applicationId;
            }
            this.Id = id;
            // use default value if no "pipelineTraceEvents" provided
            if (pipelineTraceEvents == null)
            {
                this.PipelineTraceEvents = [];
            }
            else
            {
                this.PipelineTraceEvents = pipelineTraceEvents;
            }
            this.CreatedAt = createdAt;
        }
        
        /// <summary>
        /// The UUID of this usage event.
        /// </summary>
        /// <value>The UUID of this usage event.</value>
        [DataMember(Name="_id", EmitDefaultValue=false)]
        public Object Id { get; set; }

        /// <summary>
        /// The UUID of the application associated with this usage event.
        /// </summary>
        /// <value>The UUID of the application associated with this usage event.</value>
        [DataMember(Name="application_id", EmitDefaultValue=false)]
        public Object ApplicationId { get; set; }

        /// <summary>
        /// Gets or Sets PipelineTraceEvents
        /// </summary>
        [DataMember(Name="pipeline_trace_events", EmitDefaultValue=false)]
        public Object PipelineTraceEvents { get; set; }

        /// <summary>
        /// Event creation date.
        /// </summary>
        /// <value>Event creation date.</value>
        [DataMember(Name="created_at", EmitDefaultValue=false)]
        public Object CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApplicationQueryPipelineTraceDataModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("  PipelineTraceEvents: ").Append(PipelineTraceEvents).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApplicationQueryPipelineTraceDataModel);
        }

        /// <summary>
        /// Returns true if ApplicationQueryPipelineTraceDataModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ApplicationQueryPipelineTraceDataModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicationQueryPipelineTraceDataModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ApplicationId == input.ApplicationId ||
                    (this.ApplicationId != null &&
                    this.ApplicationId.Equals(input.ApplicationId))
                ) && 
                (
                    this.PipelineTraceEvents == input.PipelineTraceEvents ||
                    (this.PipelineTraceEvents != null &&
                    this.PipelineTraceEvents.Equals(input.PipelineTraceEvents))
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ApplicationId != null)
                    hashCode = hashCode * 59 + this.ApplicationId.GetHashCode();
                if (this.PipelineTraceEvents != null)
                    hashCode = hashCode * 59 + this.PipelineTraceEvents.GetHashCode();
                if (this.CreatedAt != null)
                    hashCode = hashCode * 59 + this.CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
