/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// BodyCreatesAReferenceObjectV3RagReferenceObjectsPost
    /// </summary>
    [DataContract]
        public partial class BodyCreatesAReferenceObjectV3RagReferenceObjectsPost :  IEquatable<BodyCreatesAReferenceObjectV3RagReferenceObjectsPost>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyCreatesAReferenceObjectV3RagReferenceObjectsPost" /> class.
        /// </summary>
        /// <param name="uploadFile">uploadFile (required).</param>
        public BodyCreatesAReferenceObjectV3RagReferenceObjectsPost(Object uploadFile = default(Object))
        {
            // to ensure "uploadFile" is required (not null)
            if (uploadFile == null)
            {
                throw new InvalidDataException("uploadFile is a required property for BodyCreatesAReferenceObjectV3RagReferenceObjectsPost and cannot be null");
            }
            else
            {
                this.UploadFile = uploadFile;
            }
        }
        
        /// <summary>
        /// Gets or Sets UploadFile
        /// </summary>
        [DataMember(Name="upload_file", EmitDefaultValue=false)]
        public Object UploadFile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BodyCreatesAReferenceObjectV3RagReferenceObjectsPost {\n");
            sb.Append("  UploadFile: ").Append(UploadFile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BodyCreatesAReferenceObjectV3RagReferenceObjectsPost);
        }

        /// <summary>
        /// Returns true if BodyCreatesAReferenceObjectV3RagReferenceObjectsPost instances are equal
        /// </summary>
        /// <param name="input">Instance of BodyCreatesAReferenceObjectV3RagReferenceObjectsPost to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BodyCreatesAReferenceObjectV3RagReferenceObjectsPost input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.UploadFile == input.UploadFile ||
                    (this.UploadFile != null &&
                    this.UploadFile.Equals(input.UploadFile))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UploadFile != null)
                    hashCode = hashCode * 59 + this.UploadFile.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
