/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateConversationMessageResponseModel
    /// </summary>
    [DataContract]
        public partial class CreateConversationMessageResponseModel :  IEquatable<CreateConversationMessageResponseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateConversationMessageResponseModel" /> class.
        /// </summary>
        /// <param name="question">The question (message) created by the user. (required).</param>
        /// <param name="response">The response from the LLM. (required).</param>
        /// <param name="referenceObjectExcerpts">referenceObjectExcerpts (default to []).</param>
        /// <param name="queryPipelineId">Used query pipeline. (required).</param>
        /// <param name="llmInferenceProviderId">Used LLM inference provider. (required).</param>
        /// <param name="llmModelId">Used LLM inference provider. (required).</param>
        /// <param name="usageInfo">Request usage information. (required).</param>
        /// <param name="pipelineTrace">Pipeline trace..</param>
        public CreateConversationMessageResponseModel(ConversationMessageDataModel question = default(ConversationMessageDataModel), ConversationMessageDataModel response = default(ConversationMessageDataModel), Object referenceObjectExcerpts = [], QueryPipelineID queryPipelineId = default(QueryPipelineID), LLMInferenceProviderID llmInferenceProviderId = default(LLMInferenceProviderID), LLMModelID llmModelId = default(LLMModelID), UsageInfoModel usageInfo = default(UsageInfoModel), Object pipelineTrace = default(Object))
        {
            // to ensure "question" is required (not null)
            if (question == null)
            {
                throw new InvalidDataException("question is a required property for CreateConversationMessageResponseModel and cannot be null");
            }
            else
            {
                this.Question = question;
            }
            // to ensure "response" is required (not null)
            if (response == null)
            {
                throw new InvalidDataException("response is a required property for CreateConversationMessageResponseModel and cannot be null");
            }
            else
            {
                this.Response = response;
            }
            // to ensure "queryPipelineId" is required (not null)
            if (queryPipelineId == null)
            {
                throw new InvalidDataException("queryPipelineId is a required property for CreateConversationMessageResponseModel and cannot be null");
            }
            else
            {
                this.QueryPipelineId = queryPipelineId;
            }
            // to ensure "llmInferenceProviderId" is required (not null)
            if (llmInferenceProviderId == null)
            {
                throw new InvalidDataException("llmInferenceProviderId is a required property for CreateConversationMessageResponseModel and cannot be null");
            }
            else
            {
                this.LlmInferenceProviderId = llmInferenceProviderId;
            }
            // to ensure "llmModelId" is required (not null)
            if (llmModelId == null)
            {
                throw new InvalidDataException("llmModelId is a required property for CreateConversationMessageResponseModel and cannot be null");
            }
            else
            {
                this.LlmModelId = llmModelId;
            }
            // to ensure "usageInfo" is required (not null)
            if (usageInfo == null)
            {
                throw new InvalidDataException("usageInfo is a required property for CreateConversationMessageResponseModel and cannot be null");
            }
            else
            {
                this.UsageInfo = usageInfo;
            }
            // use default value if no "referenceObjectExcerpts" provided
            if (referenceObjectExcerpts == null)
            {
                this.ReferenceObjectExcerpts = [];
            }
            else
            {
                this.ReferenceObjectExcerpts = referenceObjectExcerpts;
            }
            this.PipelineTrace = pipelineTrace;
        }
        
        /// <summary>
        /// The question (message) created by the user.
        /// </summary>
        /// <value>The question (message) created by the user.</value>
        [DataMember(Name="question", EmitDefaultValue=false)]
        public ConversationMessageDataModel Question { get; set; }

        /// <summary>
        /// The response from the LLM.
        /// </summary>
        /// <value>The response from the LLM.</value>
        [DataMember(Name="response", EmitDefaultValue=false)]
        public ConversationMessageDataModel Response { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceObjectExcerpts
        /// </summary>
        [DataMember(Name="reference_object_excerpts", EmitDefaultValue=false)]
        public Object ReferenceObjectExcerpts { get; set; }

        /// <summary>
        /// Used query pipeline.
        /// </summary>
        /// <value>Used query pipeline.</value>
        [DataMember(Name="query_pipeline_id", EmitDefaultValue=false)]
        public QueryPipelineID QueryPipelineId { get; set; }

        /// <summary>
        /// Used LLM inference provider.
        /// </summary>
        /// <value>Used LLM inference provider.</value>
        [DataMember(Name="llm_inference_provider_id", EmitDefaultValue=false)]
        public LLMInferenceProviderID LlmInferenceProviderId { get; set; }

        /// <summary>
        /// Used LLM inference provider.
        /// </summary>
        /// <value>Used LLM inference provider.</value>
        [DataMember(Name="llm_model_id", EmitDefaultValue=false)]
        public LLMModelID LlmModelId { get; set; }

        /// <summary>
        /// Request usage information.
        /// </summary>
        /// <value>Request usage information.</value>
        [DataMember(Name="usage_info", EmitDefaultValue=false)]
        public UsageInfoModel UsageInfo { get; set; }

        /// <summary>
        /// Pipeline trace.
        /// </summary>
        /// <value>Pipeline trace.</value>
        [DataMember(Name="pipeline_trace", EmitDefaultValue=false)]
        public Object PipelineTrace { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateConversationMessageResponseModel {\n");
            sb.Append("  Question: ").Append(Question).Append("\n");
            sb.Append("  Response: ").Append(Response).Append("\n");
            sb.Append("  ReferenceObjectExcerpts: ").Append(ReferenceObjectExcerpts).Append("\n");
            sb.Append("  QueryPipelineId: ").Append(QueryPipelineId).Append("\n");
            sb.Append("  LlmInferenceProviderId: ").Append(LlmInferenceProviderId).Append("\n");
            sb.Append("  LlmModelId: ").Append(LlmModelId).Append("\n");
            sb.Append("  UsageInfo: ").Append(UsageInfo).Append("\n");
            sb.Append("  PipelineTrace: ").Append(PipelineTrace).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateConversationMessageResponseModel);
        }

        /// <summary>
        /// Returns true if CreateConversationMessageResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateConversationMessageResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateConversationMessageResponseModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Question == input.Question ||
                    (this.Question != null &&
                    this.Question.Equals(input.Question))
                ) && 
                (
                    this.Response == input.Response ||
                    (this.Response != null &&
                    this.Response.Equals(input.Response))
                ) && 
                (
                    this.ReferenceObjectExcerpts == input.ReferenceObjectExcerpts ||
                    (this.ReferenceObjectExcerpts != null &&
                    this.ReferenceObjectExcerpts.Equals(input.ReferenceObjectExcerpts))
                ) && 
                (
                    this.QueryPipelineId == input.QueryPipelineId ||
                    (this.QueryPipelineId != null &&
                    this.QueryPipelineId.Equals(input.QueryPipelineId))
                ) && 
                (
                    this.LlmInferenceProviderId == input.LlmInferenceProviderId ||
                    (this.LlmInferenceProviderId != null &&
                    this.LlmInferenceProviderId.Equals(input.LlmInferenceProviderId))
                ) && 
                (
                    this.LlmModelId == input.LlmModelId ||
                    (this.LlmModelId != null &&
                    this.LlmModelId.Equals(input.LlmModelId))
                ) && 
                (
                    this.UsageInfo == input.UsageInfo ||
                    (this.UsageInfo != null &&
                    this.UsageInfo.Equals(input.UsageInfo))
                ) && 
                (
                    this.PipelineTrace == input.PipelineTrace ||
                    (this.PipelineTrace != null &&
                    this.PipelineTrace.Equals(input.PipelineTrace))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Question != null)
                    hashCode = hashCode * 59 + this.Question.GetHashCode();
                if (this.Response != null)
                    hashCode = hashCode * 59 + this.Response.GetHashCode();
                if (this.ReferenceObjectExcerpts != null)
                    hashCode = hashCode * 59 + this.ReferenceObjectExcerpts.GetHashCode();
                if (this.QueryPipelineId != null)
                    hashCode = hashCode * 59 + this.QueryPipelineId.GetHashCode();
                if (this.LlmInferenceProviderId != null)
                    hashCode = hashCode * 59 + this.LlmInferenceProviderId.GetHashCode();
                if (this.LlmModelId != null)
                    hashCode = hashCode * 59 + this.LlmModelId.GetHashCode();
                if (this.UsageInfo != null)
                    hashCode = hashCode * 59 + this.UsageInfo.GetHashCode();
                if (this.PipelineTrace != null)
                    hashCode = hashCode * 59 + this.PipelineTrace.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
