/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateLLMCompletionRequestModel
    /// </summary>
    [DataContract]
        public partial class CreateLLMCompletionRequestModel :  IEquatable<CreateLLMCompletionRequestModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLLMCompletionRequestModel" /> class.
        /// </summary>
        /// <param name="prompt">Semantic/keyword based prompt. (required).</param>
        /// <param name="temperature">LLM model temperature (default to 0.8).</param>
        /// <param name="outputSchema">Optional output schema -                          see https://python.langchain.com/docs/how_to/structured_output/#the-with_structured_output-method for more information.                     .</param>
        public CreateLLMCompletionRequestModel(Object prompt = default(Object), Object temperature = 0.8, Object outputSchema = default(Object))
        {
            // to ensure "prompt" is required (not null)
            if (prompt == null)
            {
                throw new InvalidDataException("prompt is a required property for CreateLLMCompletionRequestModel and cannot be null");
            }
            else
            {
                this.Prompt = prompt;
            }
            // use default value if no "temperature" provided
            if (temperature == null)
            {
                this.Temperature = 0.8;
            }
            else
            {
                this.Temperature = temperature;
            }
            this.OutputSchema = outputSchema;
        }
        
        /// <summary>
        /// Semantic/keyword based prompt.
        /// </summary>
        /// <value>Semantic/keyword based prompt.</value>
        [DataMember(Name="prompt", EmitDefaultValue=false)]
        public Object Prompt { get; set; }

        /// <summary>
        /// LLM model temperature
        /// </summary>
        /// <value>LLM model temperature</value>
        [DataMember(Name="temperature", EmitDefaultValue=false)]
        public Object Temperature { get; set; }

        /// <summary>
        /// Optional output schema -                          see https://python.langchain.com/docs/how_to/structured_output/#the-with_structured_output-method for more information.                     
        /// </summary>
        /// <value>Optional output schema -                          see https://python.langchain.com/docs/how_to/structured_output/#the-with_structured_output-method for more information.                     </value>
        [DataMember(Name="output_schema", EmitDefaultValue=false)]
        public Object OutputSchema { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateLLMCompletionRequestModel {\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  Temperature: ").Append(Temperature).Append("\n");
            sb.Append("  OutputSchema: ").Append(OutputSchema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateLLMCompletionRequestModel);
        }

        /// <summary>
        /// Returns true if CreateLLMCompletionRequestModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateLLMCompletionRequestModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateLLMCompletionRequestModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Prompt == input.Prompt ||
                    (this.Prompt != null &&
                    this.Prompt.Equals(input.Prompt))
                ) && 
                (
                    this.Temperature == input.Temperature ||
                    (this.Temperature != null &&
                    this.Temperature.Equals(input.Temperature))
                ) && 
                (
                    this.OutputSchema == input.OutputSchema ||
                    (this.OutputSchema != null &&
                    this.OutputSchema.Equals(input.OutputSchema))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Prompt != null)
                    hashCode = hashCode * 59 + this.Prompt.GetHashCode();
                if (this.Temperature != null)
                    hashCode = hashCode * 59 + this.Temperature.GetHashCode();
                if (this.OutputSchema != null)
                    hashCode = hashCode * 59 + this.OutputSchema.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
