/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateReferenceObjectSearchResponseModel
    /// </summary>
    [DataContract]
        public partial class CreateReferenceObjectSearchResponseModel :  IEquatable<CreateReferenceObjectSearchResponseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReferenceObjectSearchResponseModel" /> class.
        /// </summary>
        /// <param name="referenceObjectExcerpts">A list of excerpts from reference objects matching search parameters. (required).</param>
        public CreateReferenceObjectSearchResponseModel(Object referenceObjectExcerpts = default(Object))
        {
            // to ensure "referenceObjectExcerpts" is required (not null)
            if (referenceObjectExcerpts == null)
            {
                throw new InvalidDataException("referenceObjectExcerpts is a required property for CreateReferenceObjectSearchResponseModel and cannot be null");
            }
            else
            {
                this.ReferenceObjectExcerpts = referenceObjectExcerpts;
            }
        }
        
        /// <summary>
        /// A list of excerpts from reference objects matching search parameters.
        /// </summary>
        /// <value>A list of excerpts from reference objects matching search parameters.</value>
        [DataMember(Name="reference_object_excerpts", EmitDefaultValue=false)]
        public Object ReferenceObjectExcerpts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateReferenceObjectSearchResponseModel {\n");
            sb.Append("  ReferenceObjectExcerpts: ").Append(ReferenceObjectExcerpts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateReferenceObjectSearchResponseModel);
        }

        /// <summary>
        /// Returns true if CreateReferenceObjectSearchResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateReferenceObjectSearchResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateReferenceObjectSearchResponseModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReferenceObjectExcerpts == input.ReferenceObjectExcerpts ||
                    (this.ReferenceObjectExcerpts != null &&
                    this.ReferenceObjectExcerpts.Equals(input.ReferenceObjectExcerpts))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReferenceObjectExcerpts != null)
                    hashCode = hashCode * 59 + this.ReferenceObjectExcerpts.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
