/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateReferenceObjectSearchRequestModel
    /// </summary>
    [DataContract]
        public partial class CreateReferenceObjectSearchRequestModel :  IEquatable<CreateReferenceObjectSearchRequestModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReferenceObjectSearchRequestModel" /> class.
        /// </summary>
        /// <param name="prompt">Semantic/keyword based prompt. (required).</param>
        /// <param name="includeReferenceObjects">Explicitly include specified reference objects when searching. Setting this will limit search only to reference objects specified here..</param>
        public CreateReferenceObjectSearchRequestModel(Object prompt = default(Object), Object includeReferenceObjects = default(Object))
        {
            // to ensure "prompt" is required (not null)
            if (prompt == null)
            {
                throw new InvalidDataException("prompt is a required property for CreateReferenceObjectSearchRequestModel and cannot be null");
            }
            else
            {
                this.Prompt = prompt;
            }
            this.IncludeReferenceObjects = includeReferenceObjects;
        }
        
        /// <summary>
        /// Semantic/keyword based prompt.
        /// </summary>
        /// <value>Semantic/keyword based prompt.</value>
        [DataMember(Name="prompt", EmitDefaultValue=false)]
        public Object Prompt { get; set; }

        /// <summary>
        /// Explicitly include specified reference objects when searching. Setting this will limit search only to reference objects specified here.
        /// </summary>
        /// <value>Explicitly include specified reference objects when searching. Setting this will limit search only to reference objects specified here.</value>
        [DataMember(Name="include_reference_objects", EmitDefaultValue=false)]
        public Object IncludeReferenceObjects { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateReferenceObjectSearchRequestModel {\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("  IncludeReferenceObjects: ").Append(IncludeReferenceObjects).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateReferenceObjectSearchRequestModel);
        }

        /// <summary>
        /// Returns true if CreateReferenceObjectSearchRequestModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateReferenceObjectSearchRequestModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateReferenceObjectSearchRequestModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Prompt == input.Prompt ||
                    (this.Prompt != null &&
                    this.Prompt.Equals(input.Prompt))
                ) && 
                (
                    this.IncludeReferenceObjects == input.IncludeReferenceObjects ||
                    (this.IncludeReferenceObjects != null &&
                    this.IncludeReferenceObjects.Equals(input.IncludeReferenceObjects))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Prompt != null)
                    hashCode = hashCode * 59 + this.Prompt.GetHashCode();
                if (this.IncludeReferenceObjects != null)
                    hashCode = hashCode * 59 + this.IncludeReferenceObjects.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
