/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateLLMCompletionResponseModel
    /// </summary>
    [DataContract]
        public partial class CreateLLMCompletionResponseModel :  IEquatable<CreateLLMCompletionResponseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateLLMCompletionResponseModel" /> class.
        /// </summary>
        /// <param name="llmInferenceProviderId">Used LLM inference provider. (required).</param>
        /// <param name="llmModelId">Used LLM inference provider. (required).</param>
        /// <param name="content">The response from the LLM. (required).</param>
        /// <param name="usageInfo">Request usage information. (required).</param>
        public CreateLLMCompletionResponseModel(LLMInferenceProviderID llmInferenceProviderId = default(LLMInferenceProviderID), LLMModelID llmModelId = default(LLMModelID), Object content = default(Object), UsageInfoModel usageInfo = default(UsageInfoModel))
        {
            // to ensure "llmInferenceProviderId" is required (not null)
            if (llmInferenceProviderId == null)
            {
                throw new InvalidDataException("llmInferenceProviderId is a required property for CreateLLMCompletionResponseModel and cannot be null");
            }
            else
            {
                this.LlmInferenceProviderId = llmInferenceProviderId;
            }
            // to ensure "llmModelId" is required (not null)
            if (llmModelId == null)
            {
                throw new InvalidDataException("llmModelId is a required property for CreateLLMCompletionResponseModel and cannot be null");
            }
            else
            {
                this.LlmModelId = llmModelId;
            }
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new InvalidDataException("content is a required property for CreateLLMCompletionResponseModel and cannot be null");
            }
            else
            {
                this.Content = content;
            }
            // to ensure "usageInfo" is required (not null)
            if (usageInfo == null)
            {
                throw new InvalidDataException("usageInfo is a required property for CreateLLMCompletionResponseModel and cannot be null");
            }
            else
            {
                this.UsageInfo = usageInfo;
            }
        }
        
        /// <summary>
        /// Used LLM inference provider.
        /// </summary>
        /// <value>Used LLM inference provider.</value>
        [DataMember(Name="llm_inference_provider_id", EmitDefaultValue=false)]
        public LLMInferenceProviderID LlmInferenceProviderId { get; set; }

        /// <summary>
        /// Used LLM inference provider.
        /// </summary>
        /// <value>Used LLM inference provider.</value>
        [DataMember(Name="llm_model_id", EmitDefaultValue=false)]
        public LLMModelID LlmModelId { get; set; }

        /// <summary>
        /// The response from the LLM.
        /// </summary>
        /// <value>The response from the LLM.</value>
        [DataMember(Name="content", EmitDefaultValue=false)]
        public Object Content { get; set; }

        /// <summary>
        /// Request usage information.
        /// </summary>
        /// <value>Request usage information.</value>
        [DataMember(Name="usage_info", EmitDefaultValue=false)]
        public UsageInfoModel UsageInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateLLMCompletionResponseModel {\n");
            sb.Append("  LlmInferenceProviderId: ").Append(LlmInferenceProviderId).Append("\n");
            sb.Append("  LlmModelId: ").Append(LlmModelId).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  UsageInfo: ").Append(UsageInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateLLMCompletionResponseModel);
        }

        /// <summary>
        /// Returns true if CreateLLMCompletionResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateLLMCompletionResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateLLMCompletionResponseModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LlmInferenceProviderId == input.LlmInferenceProviderId ||
                    (this.LlmInferenceProviderId != null &&
                    this.LlmInferenceProviderId.Equals(input.LlmInferenceProviderId))
                ) && 
                (
                    this.LlmModelId == input.LlmModelId ||
                    (this.LlmModelId != null &&
                    this.LlmModelId.Equals(input.LlmModelId))
                ) && 
                (
                    this.Content == input.Content ||
                    (this.Content != null &&
                    this.Content.Equals(input.Content))
                ) && 
                (
                    this.UsageInfo == input.UsageInfo ||
                    (this.UsageInfo != null &&
                    this.UsageInfo.Equals(input.UsageInfo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LlmInferenceProviderId != null)
                    hashCode = hashCode * 59 + this.LlmInferenceProviderId.GetHashCode();
                if (this.LlmModelId != null)
                    hashCode = hashCode * 59 + this.LlmModelId.GetHashCode();
                if (this.Content != null)
                    hashCode = hashCode * 59 + this.Content.GetHashCode();
                if (this.UsageInfo != null)
                    hashCode = hashCode * 59 + this.UsageInfo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
