/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines EmbeddingModelID
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum EmbeddingModelID
    {
        /// <summary>
        /// Enum Default for value: default
        /// </summary>
        [EnumMember(Value = "default")]
        Default = 1,
        /// <summary>
        /// Enum AzureOpenaiTextEmbedding3Small for value: azure-openai.text-embedding-3-small
        /// </summary>
        [EnumMember(Value = "azure-openai.text-embedding-3-small")]
        AzureOpenaiTextEmbedding3Small = 2,
        /// <summary>
        /// Enum AzureOpenaiTextEmbedding3Large for value: azure-openai.text-embedding-3-large
        /// </summary>
        [EnumMember(Value = "azure-openai.text-embedding-3-large")]
        AzureOpenaiTextEmbedding3Large = 3,
        /// <summary>
        /// Enum AzureOpenaiTextEmbeddingAda002 for value: azure-openai.text-embedding-ada-002
        /// </summary>
        [EnumMember(Value = "azure-openai.text-embedding-ada-002")]
        AzureOpenaiTextEmbeddingAda002 = 4,
        /// <summary>
        /// Enum OpenaiTextEmbedding3Small for value: openai.text-embedding-3-small
        /// </summary>
        [EnumMember(Value = "openai.text-embedding-3-small")]
        OpenaiTextEmbedding3Small = 5,
        /// <summary>
        /// Enum OpenaiTextEmbedding3Large for value: openai.text-embedding-3-large
        /// </summary>
        [EnumMember(Value = "openai.text-embedding-3-large")]
        OpenaiTextEmbedding3Large = 6,
        /// <summary>
        /// Enum OpenaiTextEmbeddingAda002 for value: openai.text-embedding-ada-002
        /// </summary>
        [EnumMember(Value = "openai.text-embedding-ada-002")]
        OpenaiTextEmbeddingAda002 = 7,
        /// <summary>
        /// Enum BedrockAmazonTitanEmbedTextV1 for value: bedrock.amazon-titan-embed-text-v1
        /// </summary>
        [EnumMember(Value = "bedrock.amazon-titan-embed-text-v1")]
        BedrockAmazonTitanEmbedTextV1 = 8,
        /// <summary>
        /// Enum BedrockAmazonTitanEmbedTextV2 for value: bedrock.amazon-titan-embed-text-v2
        /// </summary>
        [EnumMember(Value = "bedrock.amazon-titan-embed-text-v2")]
        BedrockAmazonTitanEmbedTextV2 = 9,
        /// <summary>
        /// Enum BedrockCohereEmbedEnglishV3 for value: bedrock.cohere-embed-english-v3
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-english-v3")]
        BedrockCohereEmbedEnglishV3 = 10,
        /// <summary>
        /// Enum BedrockCohereEmbedEnglishLightV3 for value: bedrock.cohere-embed-english-light-v3
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-english-light-v3")]
        BedrockCohereEmbedEnglishLightV3 = 11,
        /// <summary>
        /// Enum BedrockCohereEmbedEnglishV2 for value: bedrock.cohere-embed-english-v2
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-english-v2")]
        BedrockCohereEmbedEnglishV2 = 12,
        /// <summary>
        /// Enum BedrockCohereEmbedEnglishLightV2 for value: bedrock.cohere-embed-english-light-v2
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-english-light-v2")]
        BedrockCohereEmbedEnglishLightV2 = 13,
        /// <summary>
        /// Enum BedrockCohereEmbedMultilingualV3 for value: bedrock.cohere-embed-multilingual-v3
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-multilingual-v3")]
        BedrockCohereEmbedMultilingualV3 = 14,
        /// <summary>
        /// Enum BedrockCohereEmbedMultilingualLight for value: bedrock.cohere-embed-multilingual-light
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-multilingual-light")]
        BedrockCohereEmbedMultilingualLight = 15,
        /// <summary>
        /// Enum BedrockCohereEmbedMultilingualV2 for value: bedrock.cohere-embed-multilingual-v2
        /// </summary>
        [EnumMember(Value = "bedrock.cohere-embed-multilingual-v2")]
        BedrockCohereEmbedMultilingualV2 = 16,
        /// <summary>
        /// Enum FastembedBAAIBgeSmallEnV15 for value: fastembed.BAAI-bge-small-en-v1.5
        /// </summary>
        [EnumMember(Value = "fastembed.BAAI-bge-small-en-v1.5")]
        FastembedBAAIBgeSmallEnV15 = 17,
        /// <summary>
        /// Enum FastembedBAAIBgeBaseEnV15 for value: fastembed.BAAI-bge-base-en-v1.5
        /// </summary>
        [EnumMember(Value = "fastembed.BAAI-bge-base-en-v1.5")]
        FastembedBAAIBgeBaseEnV15 = 18,
        /// <summary>
        /// Enum FastembedBAAIBgeLargeEnV15 for value: fastembed.BAAI-bge-large-en-v1.5
        /// </summary>
        [EnumMember(Value = "fastembed.BAAI-bge-large-en-v1.5")]
        FastembedBAAIBgeLargeEnV15 = 19,
        /// <summary>
        /// Enum FastembedSnowflakeArcticEmbedXs for value: fastembed.snowflake-arctic-embed-xs
        /// </summary>
        [EnumMember(Value = "fastembed.snowflake-arctic-embed-xs")]
        FastembedSnowflakeArcticEmbedXs = 20,
        /// <summary>
        /// Enum FastembedSnowflakeArcticEmbedS for value: fastembed.snowflake-arctic-embed-s
        /// </summary>
        [EnumMember(Value = "fastembed.snowflake-arctic-embed-s")]
        FastembedSnowflakeArcticEmbedS = 21,
        /// <summary>
        /// Enum FastembedSnowflakeArcticEmbedMLong for value: fastembed.snowflake-arctic-embed-m-long
        /// </summary>
        [EnumMember(Value = "fastembed.snowflake-arctic-embed-m-long")]
        FastembedSnowflakeArcticEmbedMLong = 22,
        /// <summary>
        /// Enum FastembedSnowflakeArcticEmbedL for value: fastembed.snowflake-arctic-embed-l
        /// </summary>
        [EnumMember(Value = "fastembed.snowflake-arctic-embed-l")]
        FastembedSnowflakeArcticEmbedL = 23,
        /// <summary>
        /// Enum FastembedSentenceTransformersAllMiniLML6V2 for value: fastembed.sentence-transformers-all-MiniLM-L6-v2
        /// </summary>
        [EnumMember(Value = "fastembed.sentence-transformers-all-MiniLM-L6-v2")]
        FastembedSentenceTransformersAllMiniLML6V2 = 24,
        /// <summary>
        /// Enum FastembedJinaaiJinaEmbeddingsV2SmallEn for value: fastembed.jinaai-jina-embeddings-v2-small-en
        /// </summary>
        [EnumMember(Value = "fastembed.jinaai-jina-embeddings-v2-small-en")]
        FastembedJinaaiJinaEmbeddingsV2SmallEn = 25,
        /// <summary>
        /// Enum FastembedJinaaiJinaEmbeddingsV2BaseEn for value: fastembed.jinaai-jina-embeddings-v2-base-en
        /// </summary>
        [EnumMember(Value = "fastembed.jinaai-jina-embeddings-v2-base-en")]
        FastembedJinaaiJinaEmbeddingsV2BaseEn = 26,
        /// <summary>
        /// Enum FastembedNomicAiNomicEmbedTextV15Q for value: fastembed.nomic-ai-nomic-embed-text-v1.5-Q
        /// </summary>
        [EnumMember(Value = "fastembed.nomic-ai-nomic-embed-text-v1.5-Q")]
        FastembedNomicAiNomicEmbedTextV15Q = 27,
        /// <summary>
        /// Enum FastembedNomicAiNomicEmbedTextV15 for value: fastembed.nomic-ai-nomic-embed-text-v1.5
        /// </summary>
        [EnumMember(Value = "fastembed.nomic-ai-nomic-embed-text-v1.5")]
        FastembedNomicAiNomicEmbedTextV15 = 28,
        /// <summary>
        /// Enum FastembedParaphraseMultilingualMiniLML12V2 for value: fastembed.paraphrase-multilingual-MiniLM-L12-v2
        /// </summary>
        [EnumMember(Value = "fastembed.paraphrase-multilingual-MiniLM-L12-v2")]
        FastembedParaphraseMultilingualMiniLML12V2 = 29,
        /// <summary>
        /// Enum FastembedMixedbreadAiMxbaiEmbedLargeV1 for value: fastembed.mixedbread-ai-mxbai-embed-large-v1
        /// </summary>
        [EnumMember(Value = "fastembed.mixedbread-ai-mxbai-embed-large-v1")]
        FastembedMixedbreadAiMxbaiEmbedLargeV1 = 30,
        /// <summary>
        /// Enum FastembedThenlperGteLarge for value: fastembed.thenlper-gte-large
        /// </summary>
        [EnumMember(Value = "fastembed.thenlper-gte-large")]
        FastembedThenlperGteLarge = 31,
        /// <summary>
        /// Enum FastembedIntfloatMultilingualE5Large for value: fastembed.intfloat-multilingual-e5-large
        /// </summary>
        [EnumMember(Value = "fastembed.intfloat-multilingual-e5-large")]
        FastembedIntfloatMultilingualE5Large = 32,
        /// <summary>
        /// Enum MistralAiMistralEmbed for value: mistral-ai.mistral-embed
        /// </summary>
        [EnumMember(Value = "mistral-ai.mistral-embed")]
        MistralAiMistralEmbed = 33,
        /// <summary>
        /// Enum OllamaNomicEmbedText for value: ollama.nomic-embed-text
        /// </summary>
        [EnumMember(Value = "ollama.nomic-embed-text")]
        OllamaNomicEmbedText = 34,
        /// <summary>
        /// Enum OllamaMxbaiEmbedLarge for value: ollama.mxbai-embed-large
        /// </summary>
        [EnumMember(Value = "ollama.mxbai-embed-large")]
        OllamaMxbaiEmbedLarge = 35,
        /// <summary>
        /// Enum OllamaSnowflakeArcticEmbed for value: ollama.snowflake-arctic-embed
        /// </summary>
        [EnumMember(Value = "ollama.snowflake-arctic-embed")]
        OllamaSnowflakeArcticEmbed = 36,
        /// <summary>
        /// Enum OllamaSnowflakeArcticEmbed137m for value: ollama.snowflake-arctic-embed-137m
        /// </summary>
        [EnumMember(Value = "ollama.snowflake-arctic-embed-137m")]
        OllamaSnowflakeArcticEmbed137m = 37,
        /// <summary>
        /// Enum OllamaSnowflakeArcticEmbed110m for value: ollama.snowflake-arctic-embed-110m
        /// </summary>
        [EnumMember(Value = "ollama.snowflake-arctic-embed-110m")]
        OllamaSnowflakeArcticEmbed110m = 38,
        /// <summary>
        /// Enum OllamaSnowflakeArcticEmbed33m for value: ollama.snowflake-arctic-embed-33m
        /// </summary>
        [EnumMember(Value = "ollama.snowflake-arctic-embed-33m")]
        OllamaSnowflakeArcticEmbed33m = 39,
        /// <summary>
        /// Enum OllamaSnowflakeArcticEmbed22m for value: ollama.snowflake-arctic-embed-22m
        /// </summary>
        [EnumMember(Value = "ollama.snowflake-arctic-embed-22m")]
        OllamaSnowflakeArcticEmbed22m = 40,
        /// <summary>
        /// Enum OllamaSnowflakeArcticEmbed2 for value: ollama.snowflake-arctic-embed-2
        /// </summary>
        [EnumMember(Value = "ollama.snowflake-arctic-embed-2")]
        OllamaSnowflakeArcticEmbed2 = 41,
        /// <summary>
        /// Enum OllamaBgeM3 for value: ollama.bge-m3
        /// </summary>
        [EnumMember(Value = "ollama.bge-m3")]
        OllamaBgeM3 = 42,
        /// <summary>
        /// Enum OllamaBgeLarge for value: ollama.bge-large
        /// </summary>
        [EnumMember(Value = "ollama.bge-large")]
        OllamaBgeLarge = 43,
        /// <summary>
        /// Enum OllamaAllMinilm for value: ollama.all-minilm
        /// </summary>
        [EnumMember(Value = "ollama.all-minilm")]
        OllamaAllMinilm = 44,
        /// <summary>
        /// Enum OllamaAllMinilm33m for value: ollama.all-minilm-33m
        /// </summary>
        [EnumMember(Value = "ollama.all-minilm-33m")]
        OllamaAllMinilm33m = 45,
        /// <summary>
        /// Enum OllamaParaphraseMultilingual for value: ollama.paraphrase-multilingual
        /// </summary>
        [EnumMember(Value = "ollama.paraphrase-multilingual")]
        OllamaParaphraseMultilingual = 46,
        /// <summary>
        /// Enum OllamaGraniteEmbedding for value: ollama.granite-embedding
        /// </summary>
        [EnumMember(Value = "ollama.granite-embedding")]
        OllamaGraniteEmbedding = 47,
        /// <summary>
        /// Enum OllamaGraniteEmbedding278m for value: ollama.granite-embedding-278m
        /// </summary>
        [EnumMember(Value = "ollama.granite-embedding-278m")]
        OllamaGraniteEmbedding278m = 48,
        /// <summary>
        /// Enum TogetherTogethercomputerM2Bert80M32kRetrieval for value: together.togethercomputer-m2-bert-80M-32k-retrieval
        /// </summary>
        [EnumMember(Value = "together.togethercomputer-m2-bert-80M-32k-retrieval")]
        TogetherTogethercomputerM2Bert80M32kRetrieval = 49,
        /// <summary>
        /// Enum TogetherTogethercomputerM2Bert80M8kRetrieval for value: together.togethercomputer-m2-bert-80M-8k-retrieval
        /// </summary>
        [EnumMember(Value = "together.togethercomputer-m2-bert-80M-8k-retrieval")]
        TogetherTogethercomputerM2Bert80M8kRetrieval = 50,
        /// <summary>
        /// Enum TogetherTogethercomputerM2Bert80M2kRetrieval for value: together.togethercomputer-m2-bert-80M-2k-retrieval
        /// </summary>
        [EnumMember(Value = "together.togethercomputer-m2-bert-80M-2k-retrieval")]
        TogetherTogethercomputerM2Bert80M2kRetrieval = 51,
        /// <summary>
        /// Enum TogetherWhereIsAIUAELargeV1 for value: together.WhereIsAI-UAE-Large-V1
        /// </summary>
        [EnumMember(Value = "together.WhereIsAI-UAE-Large-V1")]
        TogetherWhereIsAIUAELargeV1 = 52,
        /// <summary>
        /// Enum TogetherBAAIBgeLargeEnV15 for value: together.BAAI-bge-large-en-v1.5
        /// </summary>
        [EnumMember(Value = "together.BAAI-bge-large-en-v1.5")]
        TogetherBAAIBgeLargeEnV15 = 53,
        /// <summary>
        /// Enum TogetherBAAIBgeBaseEnV15 for value: together.BAAI-bge-base-en-v1.5
        /// </summary>
        [EnumMember(Value = "together.BAAI-bge-base-en-v1.5")]
        TogetherBAAIBgeBaseEnV15 = 54,
        /// <summary>
        /// Enum VertexAiTextEmbeddingPreview0815 for value: vertex-ai.text-embedding-preview-0815
        /// </summary>
        [EnumMember(Value = "vertex-ai.text-embedding-preview-0815")]
        VertexAiTextEmbeddingPreview0815 = 55,
        /// <summary>
        /// Enum VertexAiTextEmbedding005 for value: vertex-ai.text-embedding-005
        /// </summary>
        [EnumMember(Value = "vertex-ai.text-embedding-005")]
        VertexAiTextEmbedding005 = 56,
        /// <summary>
        /// Enum VertexAiTextMultilingualEmbedding002 for value: vertex-ai.text-multilingual-embedding-002
        /// </summary>
        [EnumMember(Value = "vertex-ai.text-multilingual-embedding-002")]
        VertexAiTextMultilingualEmbedding002 = 57,
        /// <summary>
        /// Enum VertexAiTextEmbeddingPreview0409 for value: vertex-ai.text-embedding-preview-0409
        /// </summary>
        [EnumMember(Value = "vertex-ai.text-embedding-preview-0409")]
        VertexAiTextEmbeddingPreview0409 = 58,
        /// <summary>
        /// Enum VertexAiTextMultilingualEmbeddingPreview0409 for value: vertex-ai.text-multilingual-embedding-preview-0409
        /// </summary>
        [EnumMember(Value = "vertex-ai.text-multilingual-embedding-preview-0409")]
        VertexAiTextMultilingualEmbeddingPreview0409 = 59,
        /// <summary>
        /// Enum VertexAiTextembeddingGecko003 for value: vertex-ai.textembedding-gecko-003
        /// </summary>
        [EnumMember(Value = "vertex-ai.textembedding-gecko-003")]
        VertexAiTextembeddingGecko003 = 60,
        /// <summary>
        /// Enum VertexAiTextembeddingGeckoMultilingual001 for value: vertex-ai.textembedding-gecko-multilingual-001
        /// </summary>
        [EnumMember(Value = "vertex-ai.textembedding-gecko-multilingual-001")]
        VertexAiTextembeddingGeckoMultilingual001 = 61    }
}
