/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines EmbeddingInferenceProviderID
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum EmbeddingInferenceProviderID
    {
        /// <summary>
        /// Enum Openai for value: openai
        /// </summary>
        [EnumMember(Value = "openai")]
        Openai = 1,
        /// <summary>
        /// Enum AzureOpenai for value: azure-openai
        /// </summary>
        [EnumMember(Value = "azure-openai")]
        AzureOpenai = 2,
        /// <summary>
        /// Enum Ollama for value: ollama
        /// </summary>
        [EnumMember(Value = "ollama")]
        Ollama = 3,
        /// <summary>
        /// Enum Together for value: together
        /// </summary>
        [EnumMember(Value = "together")]
        Together = 4,
        /// <summary>
        /// Enum Bedrock for value: bedrock
        /// </summary>
        [EnumMember(Value = "bedrock")]
        Bedrock = 5,
        /// <summary>
        /// Enum VertexAi for value: vertex-ai
        /// </summary>
        [EnumMember(Value = "vertex-ai")]
        VertexAi = 6,
        /// <summary>
        /// Enum MistralAi for value: mistral-ai
        /// </summary>
        [EnumMember(Value = "mistral-ai")]
        MistralAi = 7,
        /// <summary>
        /// Enum Fastembed for value: fastembed
        /// </summary>
        [EnumMember(Value = "fastembed")]
        Fastembed = 8    }
}
