/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// GetLLMModelResponseModel
    /// </summary>
    [DataContract]
        public partial class GetLLMModelResponseModel :  IEquatable<GetLLMModelResponseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetLLMModelResponseModel" /> class.
        /// </summary>
        /// <param name="llmModel">Information about the selected LLM model. (required).</param>
        public GetLLMModelResponseModel(LLMModelInfo llmModel = default(LLMModelInfo))
        {
            // to ensure "llmModel" is required (not null)
            if (llmModel == null)
            {
                throw new InvalidDataException("llmModel is a required property for GetLLMModelResponseModel and cannot be null");
            }
            else
            {
                this.LlmModel = llmModel;
            }
        }
        
        /// <summary>
        /// Information about the selected LLM model.
        /// </summary>
        /// <value>Information about the selected LLM model.</value>
        [DataMember(Name="llm_model", EmitDefaultValue=false)]
        public LLMModelInfo LlmModel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetLLMModelResponseModel {\n");
            sb.Append("  LlmModel: ").Append(LlmModel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetLLMModelResponseModel);
        }

        /// <summary>
        /// Returns true if GetLLMModelResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of GetLLMModelResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetLLMModelResponseModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LlmModel == input.LlmModel ||
                    (this.LlmModel != null &&
                    this.LlmModel.Equals(input.LlmModel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LlmModel != null)
                    hashCode = hashCode * 59 + this.LlmModel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
