/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ListCorporaResponseModel
    /// </summary>
    [DataContract]
        public partial class ListCorporaResponseModel :  IEquatable<ListCorporaResponseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListCorporaResponseModel" /> class.
        /// </summary>
        /// <param name="corpora">The list of all corpora. (required).</param>
        public ListCorporaResponseModel(Object corpora = default(Object))
        {
            // to ensure "corpora" is required (not null)
            if (corpora == null)
            {
                throw new InvalidDataException("corpora is a required property for ListCorporaResponseModel and cannot be null");
            }
            else
            {
                this.Corpora = corpora;
            }
        }
        
        /// <summary>
        /// The list of all corpora.
        /// </summary>
        /// <value>The list of all corpora.</value>
        [DataMember(Name="corpora", EmitDefaultValue=false)]
        public Object Corpora { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListCorporaResponseModel {\n");
            sb.Append("  Corpora: ").Append(Corpora).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListCorporaResponseModel);
        }

        /// <summary>
        /// Returns true if ListCorporaResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ListCorporaResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListCorporaResponseModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Corpora == input.Corpora ||
                    (this.Corpora != null &&
                    this.Corpora.Equals(input.Corpora))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Corpora != null)
                    hashCode = hashCode * 59 + this.Corpora.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
