/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ListOrganizationApplicationsResponseModel
    /// </summary>
    [DataContract]
        public partial class ListOrganizationApplicationsResponseModel :  IEquatable<ListOrganizationApplicationsResponseModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListOrganizationApplicationsResponseModel" /> class.
        /// </summary>
        /// <param name="applications">The list of applications associated with this organization. (required).</param>
        public ListOrganizationApplicationsResponseModel(Object applications = default(Object))
        {
            // to ensure "applications" is required (not null)
            if (applications == null)
            {
                throw new InvalidDataException("applications is a required property for ListOrganizationApplicationsResponseModel and cannot be null");
            }
            else
            {
                this.Applications = applications;
            }
        }
        
        /// <summary>
        /// The list of applications associated with this organization.
        /// </summary>
        /// <value>The list of applications associated with this organization.</value>
        [DataMember(Name="applications", EmitDefaultValue=false)]
        public Object Applications { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListOrganizationApplicationsResponseModel {\n");
            sb.Append("  Applications: ").Append(Applications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListOrganizationApplicationsResponseModel);
        }

        /// <summary>
        /// Returns true if ListOrganizationApplicationsResponseModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ListOrganizationApplicationsResponseModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListOrganizationApplicationsResponseModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Applications == input.Applications ||
                    (this.Applications != null &&
                    this.Applications.Equals(input.Applications))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Applications != null)
                    hashCode = hashCode * 59 + this.Applications.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
