/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines LLMInferenceProviderID
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum LLMInferenceProviderID
    {
        /// <summary>
        /// Enum Anthropic for value: anthropic
        /// </summary>
        [EnumMember(Value = "anthropic")]
        Anthropic = 1,
        /// <summary>
        /// Enum AzureOpenai for value: azure-openai
        /// </summary>
        [EnumMember(Value = "azure-openai")]
        AzureOpenai = 2,
        /// <summary>
        /// Enum Bedrock for value: bedrock
        /// </summary>
        [EnumMember(Value = "bedrock")]
        Bedrock = 3,
        /// <summary>
        /// Enum MistralAi for value: mistral-ai
        /// </summary>
        [EnumMember(Value = "mistral-ai")]
        MistralAi = 4,
        /// <summary>
        /// Enum Ollama for value: ollama
        /// </summary>
        [EnumMember(Value = "ollama")]
        Ollama = 5,
        /// <summary>
        /// Enum Openai for value: openai
        /// </summary>
        [EnumMember(Value = "openai")]
        Openai = 6,
        /// <summary>
        /// Enum Together for value: together
        /// </summary>
        [EnumMember(Value = "together")]
        Together = 7,
        /// <summary>
        /// Enum VertexAi for value: vertex-ai
        /// </summary>
        [EnumMember(Value = "vertex-ai")]
        VertexAi = 8    }
}
