/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// LLMModelInfo
    /// </summary>
    [DataContract]
        public partial class LLMModelInfo :  IEquatable<LLMModelInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LLMModelInfo" /> class.
        /// </summary>
        /// <param name="contextWindowSize">The size of the context window. (required).</param>
        /// <param name="supportedLanguages">Languages supported by the LLM. (default to [&quot;english&quot;,&quot;chinese&quot;,&quot;japanese&quot;,&quot;korean&quot;,&quot;polish&quot;,&quot;spanish&quot;,&quot;german&quot;,&quot;french&quot;,&quot;italian&quot;,&quot;portuguese&quot;,&quot;arabic&quot;,&quot;hindi&quot;,&quot;others&quot;]).</param>
        /// <param name="isExpensive">Is this model expensive to run? (default to false).</param>
        /// <param name="isReasoning">Is this a reasoning model? (default to false).</param>
        /// <param name="isVision">Is this a vision model? (default to false).</param>
        /// <param name="supportsStructuredOutput">Does this model support structured output? (default to false).</param>
        /// <param name="requiresLocalInference">Does this model require local inference? (default to false).</param>
        public LLMModelInfo(Object contextWindowSize = default(Object), Object supportedLanguages = ["english","chinese","japanese","korean","polish","spanish","german","french","italian","portuguese","arabic","hindi","others"], Object isExpensive = false, Object isReasoning = false, Object isVision = false, Object supportsStructuredOutput = false, Object requiresLocalInference = false)
        {
            // to ensure "contextWindowSize" is required (not null)
            if (contextWindowSize == null)
            {
                throw new InvalidDataException("contextWindowSize is a required property for LLMModelInfo and cannot be null");
            }
            else
            {
                this.ContextWindowSize = contextWindowSize;
            }
            // use default value if no "supportedLanguages" provided
            if (supportedLanguages == null)
            {
                this.SupportedLanguages = ["english","chinese","japanese","korean","polish","spanish","german","french","italian","portuguese","arabic","hindi","others"];
            }
            else
            {
                this.SupportedLanguages = supportedLanguages;
            }
            // use default value if no "isExpensive" provided
            if (isExpensive == null)
            {
                this.IsExpensive = false;
            }
            else
            {
                this.IsExpensive = isExpensive;
            }
            // use default value if no "isReasoning" provided
            if (isReasoning == null)
            {
                this.IsReasoning = false;
            }
            else
            {
                this.IsReasoning = isReasoning;
            }
            // use default value if no "isVision" provided
            if (isVision == null)
            {
                this.IsVision = false;
            }
            else
            {
                this.IsVision = isVision;
            }
            // use default value if no "supportsStructuredOutput" provided
            if (supportsStructuredOutput == null)
            {
                this.SupportsStructuredOutput = false;
            }
            else
            {
                this.SupportsStructuredOutput = supportsStructuredOutput;
            }
            // use default value if no "requiresLocalInference" provided
            if (requiresLocalInference == null)
            {
                this.RequiresLocalInference = false;
            }
            else
            {
                this.RequiresLocalInference = requiresLocalInference;
            }
        }
        
        /// <summary>
        /// The size of the context window.
        /// </summary>
        /// <value>The size of the context window.</value>
        [DataMember(Name="context_window_size", EmitDefaultValue=false)]
        public Object ContextWindowSize { get; set; }

        /// <summary>
        /// Languages supported by the LLM.
        /// </summary>
        /// <value>Languages supported by the LLM.</value>
        [DataMember(Name="supported_languages", EmitDefaultValue=false)]
        public Object SupportedLanguages { get; set; }

        /// <summary>
        /// Is this model expensive to run?
        /// </summary>
        /// <value>Is this model expensive to run?</value>
        [DataMember(Name="is_expensive", EmitDefaultValue=false)]
        public Object IsExpensive { get; set; }

        /// <summary>
        /// Is this a reasoning model?
        /// </summary>
        /// <value>Is this a reasoning model?</value>
        [DataMember(Name="is_reasoning", EmitDefaultValue=false)]
        public Object IsReasoning { get; set; }

        /// <summary>
        /// Is this a vision model?
        /// </summary>
        /// <value>Is this a vision model?</value>
        [DataMember(Name="is_vision", EmitDefaultValue=false)]
        public Object IsVision { get; set; }

        /// <summary>
        /// Does this model support structured output?
        /// </summary>
        /// <value>Does this model support structured output?</value>
        [DataMember(Name="supports_structured_output", EmitDefaultValue=false)]
        public Object SupportsStructuredOutput { get; set; }

        /// <summary>
        /// Does this model require local inference?
        /// </summary>
        /// <value>Does this model require local inference?</value>
        [DataMember(Name="requires_local_inference", EmitDefaultValue=false)]
        public Object RequiresLocalInference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LLMModelInfo {\n");
            sb.Append("  ContextWindowSize: ").Append(ContextWindowSize).Append("\n");
            sb.Append("  SupportedLanguages: ").Append(SupportedLanguages).Append("\n");
            sb.Append("  IsExpensive: ").Append(IsExpensive).Append("\n");
            sb.Append("  IsReasoning: ").Append(IsReasoning).Append("\n");
            sb.Append("  IsVision: ").Append(IsVision).Append("\n");
            sb.Append("  SupportsStructuredOutput: ").Append(SupportsStructuredOutput).Append("\n");
            sb.Append("  RequiresLocalInference: ").Append(RequiresLocalInference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LLMModelInfo);
        }

        /// <summary>
        /// Returns true if LLMModelInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of LLMModelInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LLMModelInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ContextWindowSize == input.ContextWindowSize ||
                    (this.ContextWindowSize != null &&
                    this.ContextWindowSize.Equals(input.ContextWindowSize))
                ) && 
                (
                    this.SupportedLanguages == input.SupportedLanguages ||
                    (this.SupportedLanguages != null &&
                    this.SupportedLanguages.Equals(input.SupportedLanguages))
                ) && 
                (
                    this.IsExpensive == input.IsExpensive ||
                    (this.IsExpensive != null &&
                    this.IsExpensive.Equals(input.IsExpensive))
                ) && 
                (
                    this.IsReasoning == input.IsReasoning ||
                    (this.IsReasoning != null &&
                    this.IsReasoning.Equals(input.IsReasoning))
                ) && 
                (
                    this.IsVision == input.IsVision ||
                    (this.IsVision != null &&
                    this.IsVision.Equals(input.IsVision))
                ) && 
                (
                    this.SupportsStructuredOutput == input.SupportsStructuredOutput ||
                    (this.SupportsStructuredOutput != null &&
                    this.SupportsStructuredOutput.Equals(input.SupportsStructuredOutput))
                ) && 
                (
                    this.RequiresLocalInference == input.RequiresLocalInference ||
                    (this.RequiresLocalInference != null &&
                    this.RequiresLocalInference.Equals(input.RequiresLocalInference))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContextWindowSize != null)
                    hashCode = hashCode * 59 + this.ContextWindowSize.GetHashCode();
                if (this.SupportedLanguages != null)
                    hashCode = hashCode * 59 + this.SupportedLanguages.GetHashCode();
                if (this.IsExpensive != null)
                    hashCode = hashCode * 59 + this.IsExpensive.GetHashCode();
                if (this.IsReasoning != null)
                    hashCode = hashCode * 59 + this.IsReasoning.GetHashCode();
                if (this.IsVision != null)
                    hashCode = hashCode * 59 + this.IsVision.GetHashCode();
                if (this.SupportsStructuredOutput != null)
                    hashCode = hashCode * 59 + this.SupportsStructuredOutput.GetHashCode();
                if (this.RequiresLocalInference != null)
                    hashCode = hashCode * 59 + this.RequiresLocalInference.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
