/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// QueryPipelineTraceEvent
    /// </summary>
    [DataContract]
        public partial class QueryPipelineTraceEvent :  IEquatable<QueryPipelineTraceEvent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryPipelineTraceEvent" /> class.
        /// </summary>
        /// <param name="eventType">Event type. (required).</param>
        /// <param name="eventInputs">Event inputs. (default to []).</param>
        /// <param name="eventOutputs">Event inputs. (default to []).</param>
        /// <param name="elapsedTime">Pipeline event elapsed time. (default to 0).</param>
        public QueryPipelineTraceEvent(QueryPipelineTraceEventType eventType = default(QueryPipelineTraceEventType), Object eventInputs = [], Object eventOutputs = [], Object elapsedTime = 0)
        {
            // to ensure "eventType" is required (not null)
            if (eventType == null)
            {
                throw new InvalidDataException("eventType is a required property for QueryPipelineTraceEvent and cannot be null");
            }
            else
            {
                this.EventType = eventType;
            }
            // use default value if no "eventInputs" provided
            if (eventInputs == null)
            {
                this.EventInputs = [];
            }
            else
            {
                this.EventInputs = eventInputs;
            }
            // use default value if no "eventOutputs" provided
            if (eventOutputs == null)
            {
                this.EventOutputs = [];
            }
            else
            {
                this.EventOutputs = eventOutputs;
            }
            // use default value if no "elapsedTime" provided
            if (elapsedTime == null)
            {
                this.ElapsedTime = 0;
            }
            else
            {
                this.ElapsedTime = elapsedTime;
            }
        }
        
        /// <summary>
        /// Event type.
        /// </summary>
        /// <value>Event type.</value>
        [DataMember(Name="event_type", EmitDefaultValue=false)]
        public QueryPipelineTraceEventType EventType { get; set; }

        /// <summary>
        /// Event inputs.
        /// </summary>
        /// <value>Event inputs.</value>
        [DataMember(Name="event_inputs", EmitDefaultValue=false)]
        public Object EventInputs { get; set; }

        /// <summary>
        /// Event inputs.
        /// </summary>
        /// <value>Event inputs.</value>
        [DataMember(Name="event_outputs", EmitDefaultValue=false)]
        public Object EventOutputs { get; set; }

        /// <summary>
        /// Pipeline event elapsed time.
        /// </summary>
        /// <value>Pipeline event elapsed time.</value>
        [DataMember(Name="elapsed_time", EmitDefaultValue=false)]
        public Object ElapsedTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QueryPipelineTraceEvent {\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  EventInputs: ").Append(EventInputs).Append("\n");
            sb.Append("  EventOutputs: ").Append(EventOutputs).Append("\n");
            sb.Append("  ElapsedTime: ").Append(ElapsedTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QueryPipelineTraceEvent);
        }

        /// <summary>
        /// Returns true if QueryPipelineTraceEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of QueryPipelineTraceEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QueryPipelineTraceEvent input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EventType == input.EventType ||
                    (this.EventType != null &&
                    this.EventType.Equals(input.EventType))
                ) && 
                (
                    this.EventInputs == input.EventInputs ||
                    (this.EventInputs != null &&
                    this.EventInputs.Equals(input.EventInputs))
                ) && 
                (
                    this.EventOutputs == input.EventOutputs ||
                    (this.EventOutputs != null &&
                    this.EventOutputs.Equals(input.EventOutputs))
                ) && 
                (
                    this.ElapsedTime == input.ElapsedTime ||
                    (this.ElapsedTime != null &&
                    this.ElapsedTime.Equals(input.ElapsedTime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EventType != null)
                    hashCode = hashCode * 59 + this.EventType.GetHashCode();
                if (this.EventInputs != null)
                    hashCode = hashCode * 59 + this.EventInputs.GetHashCode();
                if (this.EventOutputs != null)
                    hashCode = hashCode * 59 + this.EventOutputs.GetHashCode();
                if (this.ElapsedTime != null)
                    hashCode = hashCode * 59 + this.ElapsedTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
