/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// UpdateCorpusRequestModel
    /// </summary>
    [DataContract]
        public partial class UpdateCorpusRequestModel :  IEquatable<UpdateCorpusRequestModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateCorpusRequestModel" /> class.
        /// </summary>
        /// <param name="name">The name of this corpus. (required).</param>
        /// <param name="prompt">System prompt for this corpus..</param>
        public UpdateCorpusRequestModel(Object name = default(Object), Object prompt = default(Object))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for UpdateCorpusRequestModel and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            this.Prompt = prompt;
        }
        
        /// <summary>
        /// The name of this corpus.
        /// </summary>
        /// <value>The name of this corpus.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public Object Name { get; set; }

        /// <summary>
        /// System prompt for this corpus.
        /// </summary>
        /// <value>System prompt for this corpus.</value>
        [DataMember(Name="prompt", EmitDefaultValue=false)]
        public Object Prompt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateCorpusRequestModel {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Prompt: ").Append(Prompt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateCorpusRequestModel);
        }

        /// <summary>
        /// Returns true if UpdateCorpusRequestModel instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateCorpusRequestModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateCorpusRequestModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Prompt == input.Prompt ||
                    (this.Prompt != null &&
                    this.Prompt.Equals(input.Prompt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Prompt != null)
                    hashCode = hashCode * 59 + this.Prompt.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
