/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConversationMessageOrigin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConversationMessageOriginTests
    {
        // TODO uncomment below to declare an instance variable for ConversationMessageOrigin
        //private ConversationMessageOrigin instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConversationMessageOrigin
            //instance = new ConversationMessageOrigin();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConversationMessageOrigin
        /// </summary>
        [Test]
        public void ConversationMessageOriginInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConversationMessageOrigin
            //Assert.IsInstanceOfType<ConversationMessageOrigin> (instance, "variable 'instance' is a ConversationMessageOrigin");
        }



    }

}
