/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreateCorpusRequestModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateCorpusRequestModelTests
    {
        // TODO uncomment below to declare an instance variable for CreateCorpusRequestModel
        //private CreateCorpusRequestModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCorpusRequestModel
            //instance = new CreateCorpusRequestModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCorpusRequestModel
        /// </summary>
        [Test]
        public void CreateCorpusRequestModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateCorpusRequestModel
            //Assert.IsInstanceOfType<CreateCorpusRequestModel> (instance, "variable 'instance' is a CreateCorpusRequestModel");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Test]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }
        /// <summary>
        /// Test the property 'EmbeddingInferenceProviderId'
        /// </summary>
        [Test]
        public void EmbeddingInferenceProviderIdTest()
        {
            // TODO unit test for the property 'EmbeddingInferenceProviderId'
        }
        /// <summary>
        /// Test the property 'EmbeddingModelId'
        /// </summary>
        [Test]
        public void EmbeddingModelIdTest()
        {
            // TODO unit test for the property 'EmbeddingModelId'
        }

    }

}
