/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ListReferenceObjectsResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListReferenceObjectsResponseModelTests
    {
        // TODO uncomment below to declare an instance variable for ListReferenceObjectsResponseModel
        //private ListReferenceObjectsResponseModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListReferenceObjectsResponseModel
            //instance = new ListReferenceObjectsResponseModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListReferenceObjectsResponseModel
        /// </summary>
        [Test]
        public void ListReferenceObjectsResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListReferenceObjectsResponseModel
            //Assert.IsInstanceOfType<ListReferenceObjectsResponseModel> (instance, "variable 'instance' is a ListReferenceObjectsResponseModel");
        }


        /// <summary>
        /// Test the property 'ReferenceObjects'
        /// </summary>
        [Test]
        public void ReferenceObjectsTest()
        {
            // TODO unit test for the property 'ReferenceObjects'
        }

    }

}
