/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReferenceObjectExcerptDataModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReferenceObjectExcerptDataModelTests
    {
        // TODO uncomment below to declare an instance variable for ReferenceObjectExcerptDataModel
        //private ReferenceObjectExcerptDataModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReferenceObjectExcerptDataModel
            //instance = new ReferenceObjectExcerptDataModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReferenceObjectExcerptDataModel
        /// </summary>
        [Test]
        public void ReferenceObjectExcerptDataModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReferenceObjectExcerptDataModel
            //Assert.IsInstanceOfType<ReferenceObjectExcerptDataModel> (instance, "variable 'instance' is a ReferenceObjectExcerptDataModel");
        }


        /// <summary>
        /// Test the property 'ReferenceObjectId'
        /// </summary>
        [Test]
        public void ReferenceObjectIdTest()
        {
            // TODO unit test for the property 'ReferenceObjectId'
        }
        /// <summary>
        /// Test the property 'PageNum'
        /// </summary>
        [Test]
        public void PageNumTest()
        {
            // TODO unit test for the property 'PageNum'
        }
        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Test]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }
        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Test]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Test]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }
        /// <summary>
        /// Test the property 'SourceUrl'
        /// </summary>
        [Test]
        public void SourceUrlTest()
        {
            // TODO unit test for the property 'SourceUrl'
        }
        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Test]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Test]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
