/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReferenceObjectDataModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReferenceObjectDataModelTests
    {
        // TODO uncomment below to declare an instance variable for ReferenceObjectDataModel
        //private ReferenceObjectDataModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReferenceObjectDataModel
            //instance = new ReferenceObjectDataModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReferenceObjectDataModel
        /// </summary>
        [Test]
        public void ReferenceObjectDataModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReferenceObjectDataModel
            //Assert.IsInstanceOfType<ReferenceObjectDataModel> (instance, "variable 'instance' is a ReferenceObjectDataModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Test]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'CorpusId'
        /// </summary>
        [Test]
        public void CorpusIdTest()
        {
            // TODO unit test for the property 'CorpusId'
        }
        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Test]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }
        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Test]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }
        /// <summary>
        /// Test the property 'SourceUrl'
        /// </summary>
        [Test]
        public void SourceUrlTest()
        {
            // TODO unit test for the property 'SourceUrl'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'EmbeddingIds'
        /// </summary>
        [Test]
        public void EmbeddingIdsTest()
        {
            // TODO unit test for the property 'EmbeddingIds'
        }
        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Test]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
