/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IChatbotconversationsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a conversation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateConversationResponseModel</returns>
        CreateConversationResponseModel CreateAConversationV3ChatbotConversationsPost (CreateConversationRequestModel body);

        /// <summary>
        /// Create A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a conversation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateConversationResponseModel</returns>
        ApiResponse<CreateConversationResponseModel> CreateAConversationV3ChatbotConversationsPostWithHttpInfo (CreateConversationRequestModel body);
        /// <summary>
        /// Create A New Message In A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a new message in a conversation along with a completion from the LLM.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>CreateConversationMessageResponseModel</returns>
        CreateConversationMessageResponseModel CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost (CreateConversationMessageRequestModel body, Object conversationId);

        /// <summary>
        /// Create A New Message In A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a new message in a conversation along with a completion from the LLM.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of CreateConversationMessageResponseModel</returns>
        ApiResponse<CreateConversationMessageResponseModel> CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostWithHttpInfo (CreateConversationMessageRequestModel body, Object conversationId);
        /// <summary>
        /// Delete A Conversation
        /// </summary>
        /// <remarks>
        /// Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Object</returns>
        Object DeleteAConversationV3ChatbotConversationsConversationIdDelete (Object conversationId);

        /// <summary>
        /// Delete A Conversation
        /// </summary>
        /// <remarks>
        /// Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DeleteAConversationV3ChatbotConversationsConversationIdDeleteWithHttpInfo (Object conversationId);
        /// <summary>
        /// Get A Conversation
        /// </summary>
        /// <remarks>
        /// Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>GetConversationResponseModel</returns>
        GetConversationResponseModel GetAConversationV3ChatbotConversationsConversationIdGet (Object conversationId);

        /// <summary>
        /// Get A Conversation
        /// </summary>
        /// <remarks>
        /// Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of GetConversationResponseModel</returns>
        ApiResponse<GetConversationResponseModel> GetAConversationV3ChatbotConversationsConversationIdGetWithHttpInfo (Object conversationId);
        /// <summary>
        /// List All Conversations
        /// </summary>
        /// <remarks>
        /// Lists all conversations.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListConversationsResponseModel</returns>
        ListConversationsResponseModel ListAllConversationsV3ChatbotConversationsGet ();

        /// <summary>
        /// List All Conversations
        /// </summary>
        /// <remarks>
        /// Lists all conversations.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListConversationsResponseModel</returns>
        ApiResponse<ListConversationsResponseModel> ListAllConversationsV3ChatbotConversationsGetWithHttpInfo ();
        /// <summary>
        /// List Conversation Messages
        /// </summary>
        /// <remarks>
        /// Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ListConversationMessagesResponseModel</returns>
        ListConversationMessagesResponseModel ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGet (Object conversationId);

        /// <summary>
        /// List Conversation Messages
        /// </summary>
        /// <remarks>
        /// Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of ListConversationMessagesResponseModel</returns>
        ApiResponse<ListConversationMessagesResponseModel> ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetWithHttpInfo (Object conversationId);
        /// <summary>
        /// Update A Conversation
        /// </summary>
        /// <remarks>
        /// Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>UpdateConversationResponseModel</returns>
        UpdateConversationResponseModel UpdateAConversationV3ChatbotConversationsConversationIdPatch (UpdateConversationRequestModel body, Object conversationId);

        /// <summary>
        /// Update A Conversation
        /// </summary>
        /// <remarks>
        /// Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of UpdateConversationResponseModel</returns>
        ApiResponse<UpdateConversationResponseModel> UpdateAConversationV3ChatbotConversationsConversationIdPatchWithHttpInfo (UpdateConversationRequestModel body, Object conversationId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a conversation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateConversationResponseModel</returns>
        System.Threading.Tasks.Task<CreateConversationResponseModel> CreateAConversationV3ChatbotConversationsPostAsync (CreateConversationRequestModel body);

        /// <summary>
        /// Create A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a conversation.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateConversationResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateConversationResponseModel>> CreateAConversationV3ChatbotConversationsPostAsyncWithHttpInfo (CreateConversationRequestModel body);
        /// <summary>
        /// Create A New Message In A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a new message in a conversation along with a completion from the LLM.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of CreateConversationMessageResponseModel</returns>
        System.Threading.Tasks.Task<CreateConversationMessageResponseModel> CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostAsync (CreateConversationMessageRequestModel body, Object conversationId);

        /// <summary>
        /// Create A New Message In A Conversation
        /// </summary>
        /// <remarks>
        /// Creates a new message in a conversation along with a completion from the LLM.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (CreateConversationMessageResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateConversationMessageResponseModel>> CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostAsyncWithHttpInfo (CreateConversationMessageRequestModel body, Object conversationId);
        /// <summary>
        /// Delete A Conversation
        /// </summary>
        /// <remarks>
        /// Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DeleteAConversationV3ChatbotConversationsConversationIdDeleteAsync (Object conversationId);

        /// <summary>
        /// Delete A Conversation
        /// </summary>
        /// <remarks>
        /// Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAConversationV3ChatbotConversationsConversationIdDeleteAsyncWithHttpInfo (Object conversationId);
        /// <summary>
        /// Get A Conversation
        /// </summary>
        /// <remarks>
        /// Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of GetConversationResponseModel</returns>
        System.Threading.Tasks.Task<GetConversationResponseModel> GetAConversationV3ChatbotConversationsConversationIdGetAsync (Object conversationId);

        /// <summary>
        /// Get A Conversation
        /// </summary>
        /// <remarks>
        /// Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (GetConversationResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetConversationResponseModel>> GetAConversationV3ChatbotConversationsConversationIdGetAsyncWithHttpInfo (Object conversationId);
        /// <summary>
        /// List All Conversations
        /// </summary>
        /// <remarks>
        /// Lists all conversations.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListConversationsResponseModel</returns>
        System.Threading.Tasks.Task<ListConversationsResponseModel> ListAllConversationsV3ChatbotConversationsGetAsync ();

        /// <summary>
        /// List All Conversations
        /// </summary>
        /// <remarks>
        /// Lists all conversations.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListConversationsResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListConversationsResponseModel>> ListAllConversationsV3ChatbotConversationsGetAsyncWithHttpInfo ();
        /// <summary>
        /// List Conversation Messages
        /// </summary>
        /// <remarks>
        /// Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ListConversationMessagesResponseModel</returns>
        System.Threading.Tasks.Task<ListConversationMessagesResponseModel> ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetAsync (Object conversationId);

        /// <summary>
        /// List Conversation Messages
        /// </summary>
        /// <remarks>
        /// Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (ListConversationMessagesResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListConversationMessagesResponseModel>> ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetAsyncWithHttpInfo (Object conversationId);
        /// <summary>
        /// Update A Conversation
        /// </summary>
        /// <remarks>
        /// Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of UpdateConversationResponseModel</returns>
        System.Threading.Tasks.Task<UpdateConversationResponseModel> UpdateAConversationV3ChatbotConversationsConversationIdPatchAsync (UpdateConversationRequestModel body, Object conversationId);

        /// <summary>
        /// Update A Conversation
        /// </summary>
        /// <remarks>
        /// Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (UpdateConversationResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateConversationResponseModel>> UpdateAConversationV3ChatbotConversationsConversationIdPatchAsyncWithHttpInfo (UpdateConversationRequestModel body, Object conversationId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ChatbotconversationsApi : IChatbotconversationsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatbotconversationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ChatbotconversationsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatbotconversationsApi"/> class
        /// </summary>
        /// <returns></returns>
        public ChatbotconversationsApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatbotconversationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ChatbotconversationsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create A Conversation Creates a conversation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateConversationResponseModel</returns>
        public CreateConversationResponseModel CreateAConversationV3ChatbotConversationsPost (CreateConversationRequestModel body)
        {
             ApiResponse<CreateConversationResponseModel> localVarResponse = CreateAConversationV3ChatbotConversationsPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A Conversation Creates a conversation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateConversationResponseModel</returns>
        public ApiResponse< CreateConversationResponseModel > CreateAConversationV3ChatbotConversationsPostWithHttpInfo (CreateConversationRequestModel body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ChatbotconversationsApi->CreateAConversationV3ChatbotConversationsPost");

            var localVarPath = "/v3/chatbot/conversations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAConversationV3ChatbotConversationsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateConversationResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateConversationResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateConversationResponseModel)));
        }

        /// <summary>
        /// Create A Conversation Creates a conversation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateConversationResponseModel</returns>
        public async System.Threading.Tasks.Task<CreateConversationResponseModel> CreateAConversationV3ChatbotConversationsPostAsync (CreateConversationRequestModel body)
        {
             ApiResponse<CreateConversationResponseModel> localVarResponse = await CreateAConversationV3ChatbotConversationsPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A Conversation Creates a conversation.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateConversationResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateConversationResponseModel>> CreateAConversationV3ChatbotConversationsPostAsyncWithHttpInfo (CreateConversationRequestModel body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ChatbotconversationsApi->CreateAConversationV3ChatbotConversationsPost");

            var localVarPath = "/v3/chatbot/conversations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAConversationV3ChatbotConversationsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateConversationResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateConversationResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateConversationResponseModel)));
        }

        /// <summary>
        /// Create A New Message In A Conversation Creates a new message in a conversation along with a completion from the LLM.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>CreateConversationMessageResponseModel</returns>
        public CreateConversationMessageResponseModel CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost (CreateConversationMessageRequestModel body, Object conversationId)
        {
             ApiResponse<CreateConversationMessageResponseModel> localVarResponse = CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostWithHttpInfo(body, conversationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A New Message In A Conversation Creates a new message in a conversation along with a completion from the LLM.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of CreateConversationMessageResponseModel</returns>
        public ApiResponse< CreateConversationMessageResponseModel > CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostWithHttpInfo (CreateConversationMessageRequestModel body, Object conversationId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ChatbotconversationsApi->CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost");
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}/messages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateConversationMessageResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateConversationMessageResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateConversationMessageResponseModel)));
        }

        /// <summary>
        /// Create A New Message In A Conversation Creates a new message in a conversation along with a completion from the LLM.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of CreateConversationMessageResponseModel</returns>
        public async System.Threading.Tasks.Task<CreateConversationMessageResponseModel> CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostAsync (CreateConversationMessageRequestModel body, Object conversationId)
        {
             ApiResponse<CreateConversationMessageResponseModel> localVarResponse = await CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostAsyncWithHttpInfo(body, conversationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A New Message In A Conversation Creates a new message in a conversation along with a completion from the LLM.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (CreateConversationMessageResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateConversationMessageResponseModel>> CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPostAsyncWithHttpInfo (CreateConversationMessageRequestModel body, Object conversationId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ChatbotconversationsApi->CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost");
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}/messages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateANewMessageInAConversationV3ChatbotConversationsConversationIdMessagesPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateConversationMessageResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateConversationMessageResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateConversationMessageResponseModel)));
        }

        /// <summary>
        /// Delete A Conversation Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Object</returns>
        public Object DeleteAConversationV3ChatbotConversationsConversationIdDelete (Object conversationId)
        {
             ApiResponse<Object> localVarResponse = DeleteAConversationV3ChatbotConversationsConversationIdDeleteWithHttpInfo(conversationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete A Conversation Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > DeleteAConversationV3ChatbotConversationsConversationIdDeleteWithHttpInfo (Object conversationId)
        {
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->DeleteAConversationV3ChatbotConversationsConversationIdDelete");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAConversationV3ChatbotConversationsConversationIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Delete A Conversation Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DeleteAConversationV3ChatbotConversationsConversationIdDeleteAsync (Object conversationId)
        {
             ApiResponse<Object> localVarResponse = await DeleteAConversationV3ChatbotConversationsConversationIdDeleteAsyncWithHttpInfo(conversationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete A Conversation Deletes the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteAConversationV3ChatbotConversationsConversationIdDeleteAsyncWithHttpInfo (Object conversationId)
        {
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->DeleteAConversationV3ChatbotConversationsConversationIdDelete");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteAConversationV3ChatbotConversationsConversationIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Get A Conversation Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>GetConversationResponseModel</returns>
        public GetConversationResponseModel GetAConversationV3ChatbotConversationsConversationIdGet (Object conversationId)
        {
             ApiResponse<GetConversationResponseModel> localVarResponse = GetAConversationV3ChatbotConversationsConversationIdGetWithHttpInfo(conversationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get A Conversation Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of GetConversationResponseModel</returns>
        public ApiResponse< GetConversationResponseModel > GetAConversationV3ChatbotConversationsConversationIdGetWithHttpInfo (Object conversationId)
        {
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->GetAConversationV3ChatbotConversationsConversationIdGet");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAConversationV3ChatbotConversationsConversationIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetConversationResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetConversationResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetConversationResponseModel)));
        }

        /// <summary>
        /// Get A Conversation Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of GetConversationResponseModel</returns>
        public async System.Threading.Tasks.Task<GetConversationResponseModel> GetAConversationV3ChatbotConversationsConversationIdGetAsync (Object conversationId)
        {
             ApiResponse<GetConversationResponseModel> localVarResponse = await GetAConversationV3ChatbotConversationsConversationIdGetAsyncWithHttpInfo(conversationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get A Conversation Returns a conversation matching the provided &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (GetConversationResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetConversationResponseModel>> GetAConversationV3ChatbotConversationsConversationIdGetAsyncWithHttpInfo (Object conversationId)
        {
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->GetAConversationV3ChatbotConversationsConversationIdGet");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAConversationV3ChatbotConversationsConversationIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetConversationResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetConversationResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetConversationResponseModel)));
        }

        /// <summary>
        /// List All Conversations Lists all conversations.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListConversationsResponseModel</returns>
        public ListConversationsResponseModel ListAllConversationsV3ChatbotConversationsGet ()
        {
             ApiResponse<ListConversationsResponseModel> localVarResponse = ListAllConversationsV3ChatbotConversationsGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List All Conversations Lists all conversations.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListConversationsResponseModel</returns>
        public ApiResponse< ListConversationsResponseModel > ListAllConversationsV3ChatbotConversationsGetWithHttpInfo ()
        {

            var localVarPath = "/v3/chatbot/conversations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAllConversationsV3ChatbotConversationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListConversationsResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListConversationsResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListConversationsResponseModel)));
        }

        /// <summary>
        /// List All Conversations Lists all conversations.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListConversationsResponseModel</returns>
        public async System.Threading.Tasks.Task<ListConversationsResponseModel> ListAllConversationsV3ChatbotConversationsGetAsync ()
        {
             ApiResponse<ListConversationsResponseModel> localVarResponse = await ListAllConversationsV3ChatbotConversationsGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List All Conversations Lists all conversations.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListConversationsResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListConversationsResponseModel>> ListAllConversationsV3ChatbotConversationsGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/v3/chatbot/conversations";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAllConversationsV3ChatbotConversationsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListConversationsResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListConversationsResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListConversationsResponseModel)));
        }

        /// <summary>
        /// List Conversation Messages Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ListConversationMessagesResponseModel</returns>
        public ListConversationMessagesResponseModel ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGet (Object conversationId)
        {
             ApiResponse<ListConversationMessagesResponseModel> localVarResponse = ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetWithHttpInfo(conversationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Conversation Messages Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of ListConversationMessagesResponseModel</returns>
        public ApiResponse< ListConversationMessagesResponseModel > ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetWithHttpInfo (Object conversationId)
        {
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGet");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}/messages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListConversationMessagesResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListConversationMessagesResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListConversationMessagesResponseModel)));
        }

        /// <summary>
        /// List Conversation Messages Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ListConversationMessagesResponseModel</returns>
        public async System.Threading.Tasks.Task<ListConversationMessagesResponseModel> ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetAsync (Object conversationId)
        {
             ApiResponse<ListConversationMessagesResponseModel> localVarResponse = await ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetAsyncWithHttpInfo(conversationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Conversation Messages Lists all messages associated with a conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (ListConversationMessagesResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListConversationMessagesResponseModel>> ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGetAsyncWithHttpInfo (Object conversationId)
        {
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGet");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}/messages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListConversationMessagesV3ChatbotConversationsConversationIdMessagesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListConversationMessagesResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListConversationMessagesResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListConversationMessagesResponseModel)));
        }

        /// <summary>
        /// Update A Conversation Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>UpdateConversationResponseModel</returns>
        public UpdateConversationResponseModel UpdateAConversationV3ChatbotConversationsConversationIdPatch (UpdateConversationRequestModel body, Object conversationId)
        {
             ApiResponse<UpdateConversationResponseModel> localVarResponse = UpdateAConversationV3ChatbotConversationsConversationIdPatchWithHttpInfo(body, conversationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update A Conversation Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>ApiResponse of UpdateConversationResponseModel</returns>
        public ApiResponse< UpdateConversationResponseModel > UpdateAConversationV3ChatbotConversationsConversationIdPatchWithHttpInfo (UpdateConversationRequestModel body, Object conversationId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ChatbotconversationsApi->UpdateAConversationV3ChatbotConversationsConversationIdPatch");
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->UpdateAConversationV3ChatbotConversationsConversationIdPatch");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Patch, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAConversationV3ChatbotConversationsConversationIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UpdateConversationResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (UpdateConversationResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(UpdateConversationResponseModel)));
        }

        /// <summary>
        /// Update A Conversation Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of UpdateConversationResponseModel</returns>
        public async System.Threading.Tasks.Task<UpdateConversationResponseModel> UpdateAConversationV3ChatbotConversationsConversationIdPatchAsync (UpdateConversationRequestModel body, Object conversationId)
        {
             ApiResponse<UpdateConversationResponseModel> localVarResponse = await UpdateAConversationV3ChatbotConversationsConversationIdPatchAsyncWithHttpInfo(body, conversationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update A Conversation Updates the conversation specified in &#x60;conversation_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="conversationId"></param>
        /// <returns>Task of ApiResponse (UpdateConversationResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<UpdateConversationResponseModel>> UpdateAConversationV3ChatbotConversationsConversationIdPatchAsyncWithHttpInfo (UpdateConversationRequestModel body, Object conversationId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ChatbotconversationsApi->UpdateAConversationV3ChatbotConversationsConversationIdPatch");
            // verify the required parameter 'conversationId' is set
            if (conversationId == null)
                throw new ApiException(400, "Missing required parameter 'conversationId' when calling ChatbotconversationsApi->UpdateAConversationV3ChatbotConversationsConversationIdPatch");

            var localVarPath = "/v3/chatbot/conversations/{conversation_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (conversationId != null) localVarPathParams.Add("conversation_id", this.Configuration.ApiClient.ParameterToString(conversationId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Patch, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAConversationV3ChatbotConversationsConversationIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UpdateConversationResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (UpdateConversationResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(UpdateConversationResponseModel)));
        }

    }
}
