/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IModelsllmsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create A Completion
        /// </summary>
        /// <remarks>
        /// Creates an LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>CreateLLMCompletionResponseModel</returns>
        CreateLLMCompletionResponseModel CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);

        /// <summary>
        /// Create A Completion
        /// </summary>
        /// <remarks>
        /// Creates an LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>ApiResponse of CreateLLMCompletionResponseModel</returns>
        ApiResponse<CreateLLMCompletionResponseModel> CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);
        /// <summary>
        /// Create A Streaming Completion
        /// </summary>
        /// <remarks>
        /// Creates a streaming LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Object</returns>
        Object CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);

        /// <summary>
        /// Create A Streaming Completion
        /// </summary>
        /// <remarks>
        /// Creates a streaming LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);
        /// <summary>
        /// Get Model Information
        /// </summary>
        /// <remarks>
        /// Gets information for a specified model.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>GetLLMModelResponseModel</returns>
        GetLLMModelResponseModel GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);

        /// <summary>
        /// Get Model Information
        /// </summary>
        /// <remarks>
        /// Gets information for a specified model.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>ApiResponse of GetLLMModelResponseModel</returns>
        ApiResponse<GetLLMModelResponseModel> GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);
        /// <summary>
        /// List All Llm Inference Providers
        /// </summary>
        /// <remarks>
        /// List all LLM inference providers.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListLLMInferenceProvidersResponseModel</returns>
        ListLLMInferenceProvidersResponseModel ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet ();

        /// <summary>
        /// List All Llm Inference Providers
        /// </summary>
        /// <remarks>
        /// List all LLM inference providers.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListLLMInferenceProvidersResponseModel</returns>
        ApiResponse<ListLLMInferenceProvidersResponseModel> ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetWithHttpInfo ();
        /// <summary>
        /// List Llm Inference Provider Models
        /// </summary>
        /// <remarks>
        /// Lists all LLM models in the provided llm inference provider.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>ListLLMInferenceProviderModelsResponseModel</returns>
        ListLLMInferenceProviderModelsResponseModel ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet (LLMInferenceProviderID llmInferenceProviderId);

        /// <summary>
        /// List Llm Inference Provider Models
        /// </summary>
        /// <remarks>
        /// Lists all LLM models in the provided llm inference provider.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>ApiResponse of ListLLMInferenceProviderModelsResponseModel</returns>
        ApiResponse<ListLLMInferenceProviderModelsResponseModel> ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create A Completion
        /// </summary>
        /// <remarks>
        /// Creates an LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of CreateLLMCompletionResponseModel</returns>
        System.Threading.Tasks.Task<CreateLLMCompletionResponseModel> CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostAsync (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);

        /// <summary>
        /// Create A Completion
        /// </summary>
        /// <remarks>
        /// Creates an LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of ApiResponse (CreateLLMCompletionResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateLLMCompletionResponseModel>> CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostAsyncWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);
        /// <summary>
        /// Create A Streaming Completion
        /// </summary>
        /// <remarks>
        /// Creates a streaming LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostAsync (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);

        /// <summary>
        /// Create A Streaming Completion
        /// </summary>
        /// <remarks>
        /// Creates a streaming LLM completion.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostAsyncWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);
        /// <summary>
        /// Get Model Information
        /// </summary>
        /// <remarks>
        /// Gets information for a specified model.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of GetLLMModelResponseModel</returns>
        System.Threading.Tasks.Task<GetLLMModelResponseModel> GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetAsync (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);

        /// <summary>
        /// Get Model Information
        /// </summary>
        /// <remarks>
        /// Gets information for a specified model.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of ApiResponse (GetLLMModelResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetLLMModelResponseModel>> GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetAsyncWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId);
        /// <summary>
        /// List All Llm Inference Providers
        /// </summary>
        /// <remarks>
        /// List all LLM inference providers.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListLLMInferenceProvidersResponseModel</returns>
        System.Threading.Tasks.Task<ListLLMInferenceProvidersResponseModel> ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetAsync ();

        /// <summary>
        /// List All Llm Inference Providers
        /// </summary>
        /// <remarks>
        /// List all LLM inference providers.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListLLMInferenceProvidersResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListLLMInferenceProvidersResponseModel>> ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetAsyncWithHttpInfo ();
        /// <summary>
        /// List Llm Inference Provider Models
        /// </summary>
        /// <remarks>
        /// Lists all LLM models in the provided llm inference provider.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>Task of ListLLMInferenceProviderModelsResponseModel</returns>
        System.Threading.Tasks.Task<ListLLMInferenceProviderModelsResponseModel> ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetAsync (LLMInferenceProviderID llmInferenceProviderId);

        /// <summary>
        /// List Llm Inference Provider Models
        /// </summary>
        /// <remarks>
        /// Lists all LLM models in the provided llm inference provider.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>Task of ApiResponse (ListLLMInferenceProviderModelsResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListLLMInferenceProviderModelsResponseModel>> ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetAsyncWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ModelsllmsApi : IModelsllmsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsllmsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ModelsllmsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsllmsApi"/> class
        /// </summary>
        /// <returns></returns>
        public ModelsllmsApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModelsllmsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ModelsllmsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create A Completion Creates an LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>CreateLLMCompletionResponseModel</returns>
        public CreateLLMCompletionResponseModel CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
             ApiResponse<CreateLLMCompletionResponseModel> localVarResponse = CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostWithHttpInfo(body, llmInferenceProviderId, llmModelId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A Completion Creates an LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>ApiResponse of CreateLLMCompletionResponseModel</returns>
        public ApiResponse< CreateLLMCompletionResponseModel > CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ModelsllmsApi->CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost");
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost");
            // verify the required parameter 'llmModelId' is set
            if (llmModelId == null)
                throw new ApiException(400, "Missing required parameter 'llmModelId' when calling ModelsllmsApi->CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            if (llmModelId != null) localVarPathParams.Add("llm_model_id", this.Configuration.ApiClient.ParameterToString(llmModelId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateLLMCompletionResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateLLMCompletionResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateLLMCompletionResponseModel)));
        }

        /// <summary>
        /// Create A Completion Creates an LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of CreateLLMCompletionResponseModel</returns>
        public async System.Threading.Tasks.Task<CreateLLMCompletionResponseModel> CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostAsync (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
             ApiResponse<CreateLLMCompletionResponseModel> localVarResponse = await CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostAsyncWithHttpInfo(body, llmInferenceProviderId, llmModelId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A Completion Creates an LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of ApiResponse (CreateLLMCompletionResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateLLMCompletionResponseModel>> CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPostAsyncWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ModelsllmsApi->CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost");
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost");
            // verify the required parameter 'llmModelId' is set
            if (llmModelId == null)
                throw new ApiException(400, "Missing required parameter 'llmModelId' when calling ModelsllmsApi->CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            if (llmModelId != null) localVarPathParams.Add("llm_model_id", this.Configuration.ApiClient.ParameterToString(llmModelId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateACompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateLLMCompletionResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateLLMCompletionResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateLLMCompletionResponseModel)));
        }

        /// <summary>
        /// Create A Streaming Completion Creates a streaming LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Object</returns>
        public Object CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
             ApiResponse<Object> localVarResponse = CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostWithHttpInfo(body, llmInferenceProviderId, llmModelId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A Streaming Completion Creates a streaming LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ModelsllmsApi->CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost");
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost");
            // verify the required parameter 'llmModelId' is set
            if (llmModelId == null)
                throw new ApiException(400, "Missing required parameter 'llmModelId' when calling ModelsllmsApi->CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}/stream";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            if (llmModelId != null) localVarPathParams.Add("llm_model_id", this.Configuration.ApiClient.ParameterToString(llmModelId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Create A Streaming Completion Creates a streaming LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostAsync (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
             ApiResponse<Object> localVarResponse = await CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostAsyncWithHttpInfo(body, llmInferenceProviderId, llmModelId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A Streaming Completion Creates a streaming LLM completion.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPostAsyncWithHttpInfo (CreateLLMCompletionRequestModel body, LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling ModelsllmsApi->CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost");
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost");
            // verify the required parameter 'llmModelId' is set
            if (llmModelId == null)
                throw new ApiException(400, "Missing required parameter 'llmModelId' when calling ModelsllmsApi->CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}/stream";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            if (llmModelId != null) localVarPathParams.Add("llm_model_id", this.Configuration.ApiClient.ParameterToString(llmModelId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAStreamingCompletionV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdStreamPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Get Model Information Gets information for a specified model.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>GetLLMModelResponseModel</returns>
        public GetLLMModelResponseModel GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
             ApiResponse<GetLLMModelResponseModel> localVarResponse = GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetWithHttpInfo(llmInferenceProviderId, llmModelId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get Model Information Gets information for a specified model.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>ApiResponse of GetLLMModelResponseModel</returns>
        public ApiResponse< GetLLMModelResponseModel > GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet");
            // verify the required parameter 'llmModelId' is set
            if (llmModelId == null)
                throw new ApiException(400, "Missing required parameter 'llmModelId' when calling ModelsllmsApi->GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            if (llmModelId != null) localVarPathParams.Add("llm_model_id", this.Configuration.ApiClient.ParameterToString(llmModelId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetLLMModelResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetLLMModelResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetLLMModelResponseModel)));
        }

        /// <summary>
        /// Get Model Information Gets information for a specified model.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of GetLLMModelResponseModel</returns>
        public async System.Threading.Tasks.Task<GetLLMModelResponseModel> GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetAsync (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
             ApiResponse<GetLLMModelResponseModel> localVarResponse = await GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetAsyncWithHttpInfo(llmInferenceProviderId, llmModelId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get Model Information Gets information for a specified model.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <param name="llmModelId"></param>
        /// <returns>Task of ApiResponse (GetLLMModelResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetLLMModelResponseModel>> GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGetAsyncWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId, LLMModelID llmModelId)
        {
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet");
            // verify the required parameter 'llmModelId' is set
            if (llmModelId == null)
                throw new ApiException(400, "Missing required parameter 'llmModelId' when calling ModelsllmsApi->GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms/{llm_model_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            if (llmModelId != null) localVarPathParams.Add("llm_model_id", this.Configuration.ApiClient.ParameterToString(llmModelId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetModelInformationV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsLlmModelIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetLLMModelResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetLLMModelResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetLLMModelResponseModel)));
        }

        /// <summary>
        /// List All Llm Inference Providers List all LLM inference providers.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListLLMInferenceProvidersResponseModel</returns>
        public ListLLMInferenceProvidersResponseModel ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet ()
        {
             ApiResponse<ListLLMInferenceProvidersResponseModel> localVarResponse = ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List All Llm Inference Providers List all LLM inference providers.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListLLMInferenceProvidersResponseModel</returns>
        public ApiResponse< ListLLMInferenceProvidersResponseModel > ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetWithHttpInfo ()
        {

            var localVarPath = "/v3/models/llm_inference_providers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListLLMInferenceProvidersResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListLLMInferenceProvidersResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListLLMInferenceProvidersResponseModel)));
        }

        /// <summary>
        /// List All Llm Inference Providers List all LLM inference providers.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListLLMInferenceProvidersResponseModel</returns>
        public async System.Threading.Tasks.Task<ListLLMInferenceProvidersResponseModel> ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetAsync ()
        {
             ApiResponse<ListLLMInferenceProvidersResponseModel> localVarResponse = await ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List All Llm Inference Providers List all LLM inference providers.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListLLMInferenceProvidersResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListLLMInferenceProvidersResponseModel>> ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/v3/models/llm_inference_providers";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAllLLMInferenceProvidersV3ModelsLlmInferenceProvidersGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListLLMInferenceProvidersResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListLLMInferenceProvidersResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListLLMInferenceProvidersResponseModel)));
        }

        /// <summary>
        /// List Llm Inference Provider Models Lists all LLM models in the provided llm inference provider.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>ListLLMInferenceProviderModelsResponseModel</returns>
        public ListLLMInferenceProviderModelsResponseModel ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet (LLMInferenceProviderID llmInferenceProviderId)
        {
             ApiResponse<ListLLMInferenceProviderModelsResponseModel> localVarResponse = ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetWithHttpInfo(llmInferenceProviderId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Llm Inference Provider Models Lists all LLM models in the provided llm inference provider.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>ApiResponse of ListLLMInferenceProviderModelsResponseModel</returns>
        public ApiResponse< ListLLMInferenceProviderModelsResponseModel > ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId)
        {
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListLLMInferenceProviderModelsResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListLLMInferenceProviderModelsResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListLLMInferenceProviderModelsResponseModel)));
        }

        /// <summary>
        /// List Llm Inference Provider Models Lists all LLM models in the provided llm inference provider.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>Task of ListLLMInferenceProviderModelsResponseModel</returns>
        public async System.Threading.Tasks.Task<ListLLMInferenceProviderModelsResponseModel> ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetAsync (LLMInferenceProviderID llmInferenceProviderId)
        {
             ApiResponse<ListLLMInferenceProviderModelsResponseModel> localVarResponse = await ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetAsyncWithHttpInfo(llmInferenceProviderId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Llm Inference Provider Models Lists all LLM models in the provided llm inference provider.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="llmInferenceProviderId"></param>
        /// <returns>Task of ApiResponse (ListLLMInferenceProviderModelsResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListLLMInferenceProviderModelsResponseModel>> ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGetAsyncWithHttpInfo (LLMInferenceProviderID llmInferenceProviderId)
        {
            // verify the required parameter 'llmInferenceProviderId' is set
            if (llmInferenceProviderId == null)
                throw new ApiException(400, "Missing required parameter 'llmInferenceProviderId' when calling ModelsllmsApi->ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet");

            var localVarPath = "/v3/models/llm_inference_providers/{llm_inference_provider_id}/llms";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (llmInferenceProviderId != null) localVarPathParams.Add("llm_inference_provider_id", this.Configuration.ApiClient.ParameterToString(llmInferenceProviderId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListLLMInferenceProviderModelsV3ModelsLlmInferenceProvidersLlmInferenceProviderIdLlmsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListLLMInferenceProviderModelsResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListLLMInferenceProviderModelsResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListLLMInferenceProviderModelsResponseModel)));
        }

    }
}
