/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IRagcorporaApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create A Corpus
        /// </summary>
        /// <remarks>
        /// Creates a corpus.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateCorpusResponseModel</returns>
        CreateCorpusResponseModel CreateACorpusV3RagCorporaPost (CreateCorpusRequestModel body);

        /// <summary>
        /// Create A Corpus
        /// </summary>
        /// <remarks>
        /// Creates a corpus.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateCorpusResponseModel</returns>
        ApiResponse<CreateCorpusResponseModel> CreateACorpusV3RagCorporaPostWithHttpInfo (CreateCorpusRequestModel body);
        /// <summary>
        /// Delete A Corpus
        /// </summary>
        /// <remarks>
        /// Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Object</returns>
        Object DeleteACorpusV3RagCorporaCorpusIdDelete (Object corpusId);

        /// <summary>
        /// Delete A Corpus
        /// </summary>
        /// <remarks>
        /// Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DeleteACorpusV3RagCorporaCorpusIdDeleteWithHttpInfo (Object corpusId);
        /// <summary>
        /// Get A Corpus
        /// </summary>
        /// <remarks>
        /// Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>GetCorpusResponseModel</returns>
        GetCorpusResponseModel GetACorpusV3RagCorporaCorpusIdGet (Object corpusId);

        /// <summary>
        /// Get A Corpus
        /// </summary>
        /// <remarks>
        /// Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of GetCorpusResponseModel</returns>
        ApiResponse<GetCorpusResponseModel> GetACorpusV3RagCorporaCorpusIdGetWithHttpInfo (Object corpusId);
        /// <summary>
        /// List All Corpora
        /// </summary>
        /// <remarks>
        /// Lists all corpora.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCorporaResponseModel</returns>
        ListCorporaResponseModel ListAllCorporaV3RagCorporaGet ();

        /// <summary>
        /// List All Corpora
        /// </summary>
        /// <remarks>
        /// Lists all corpora.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCorporaResponseModel</returns>
        ApiResponse<ListCorporaResponseModel> ListAllCorporaV3RagCorporaGetWithHttpInfo ();
        /// <summary>
        /// List Corpus Reference Objects
        /// </summary>
        /// <remarks>
        /// Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ListCorpusReferenceObjectsResponseModel</returns>
        ListCorpusReferenceObjectsResponseModel ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet (Object corpusId);

        /// <summary>
        /// List Corpus Reference Objects
        /// </summary>
        /// <remarks>
        /// Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of ListCorpusReferenceObjectsResponseModel</returns>
        ApiResponse<ListCorpusReferenceObjectsResponseModel> ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetWithHttpInfo (Object corpusId);
        /// <summary>
        /// Update A Corpus
        /// </summary>
        /// <remarks>
        /// Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>UpdateCorpusResponseModel</returns>
        UpdateCorpusResponseModel UpdateACorpusV3RagCorporaCorpusIdPatch (UpdateCorpusRequestModel body, Object corpusId);

        /// <summary>
        /// Update A Corpus
        /// </summary>
        /// <remarks>
        /// Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of UpdateCorpusResponseModel</returns>
        ApiResponse<UpdateCorpusResponseModel> UpdateACorpusV3RagCorporaCorpusIdPatchWithHttpInfo (UpdateCorpusRequestModel body, Object corpusId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create A Corpus
        /// </summary>
        /// <remarks>
        /// Creates a corpus.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateCorpusResponseModel</returns>
        System.Threading.Tasks.Task<CreateCorpusResponseModel> CreateACorpusV3RagCorporaPostAsync (CreateCorpusRequestModel body);

        /// <summary>
        /// Create A Corpus
        /// </summary>
        /// <remarks>
        /// Creates a corpus.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateCorpusResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateCorpusResponseModel>> CreateACorpusV3RagCorporaPostAsyncWithHttpInfo (CreateCorpusRequestModel body);
        /// <summary>
        /// Delete A Corpus
        /// </summary>
        /// <remarks>
        /// Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DeleteACorpusV3RagCorporaCorpusIdDeleteAsync (Object corpusId);

        /// <summary>
        /// Delete A Corpus
        /// </summary>
        /// <remarks>
        /// Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteACorpusV3RagCorporaCorpusIdDeleteAsyncWithHttpInfo (Object corpusId);
        /// <summary>
        /// Get A Corpus
        /// </summary>
        /// <remarks>
        /// Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of GetCorpusResponseModel</returns>
        System.Threading.Tasks.Task<GetCorpusResponseModel> GetACorpusV3RagCorporaCorpusIdGetAsync (Object corpusId);

        /// <summary>
        /// Get A Corpus
        /// </summary>
        /// <remarks>
        /// Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (GetCorpusResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetCorpusResponseModel>> GetACorpusV3RagCorporaCorpusIdGetAsyncWithHttpInfo (Object corpusId);
        /// <summary>
        /// List All Corpora
        /// </summary>
        /// <remarks>
        /// Lists all corpora.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListCorporaResponseModel</returns>
        System.Threading.Tasks.Task<ListCorporaResponseModel> ListAllCorporaV3RagCorporaGetAsync ();

        /// <summary>
        /// List All Corpora
        /// </summary>
        /// <remarks>
        /// Lists all corpora.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListCorporaResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListCorporaResponseModel>> ListAllCorporaV3RagCorporaGetAsyncWithHttpInfo ();
        /// <summary>
        /// List Corpus Reference Objects
        /// </summary>
        /// <remarks>
        /// Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ListCorpusReferenceObjectsResponseModel</returns>
        System.Threading.Tasks.Task<ListCorpusReferenceObjectsResponseModel> ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetAsync (Object corpusId);

        /// <summary>
        /// List Corpus Reference Objects
        /// </summary>
        /// <remarks>
        /// Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (ListCorpusReferenceObjectsResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListCorpusReferenceObjectsResponseModel>> ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetAsyncWithHttpInfo (Object corpusId);
        /// <summary>
        /// Update A Corpus
        /// </summary>
        /// <remarks>
        /// Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>Task of UpdateCorpusResponseModel</returns>
        System.Threading.Tasks.Task<UpdateCorpusResponseModel> UpdateACorpusV3RagCorporaCorpusIdPatchAsync (UpdateCorpusRequestModel body, Object corpusId);

        /// <summary>
        /// Update A Corpus
        /// </summary>
        /// <remarks>
        /// Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (UpdateCorpusResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateCorpusResponseModel>> UpdateACorpusV3RagCorporaCorpusIdPatchAsyncWithHttpInfo (UpdateCorpusRequestModel body, Object corpusId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class RagcorporaApi : IRagcorporaApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RagcorporaApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RagcorporaApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RagcorporaApi"/> class
        /// </summary>
        /// <returns></returns>
        public RagcorporaApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RagcorporaApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RagcorporaApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create A Corpus Creates a corpus.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>CreateCorpusResponseModel</returns>
        public CreateCorpusResponseModel CreateACorpusV3RagCorporaPost (CreateCorpusRequestModel body)
        {
             ApiResponse<CreateCorpusResponseModel> localVarResponse = CreateACorpusV3RagCorporaPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A Corpus Creates a corpus.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>ApiResponse of CreateCorpusResponseModel</returns>
        public ApiResponse< CreateCorpusResponseModel > CreateACorpusV3RagCorporaPostWithHttpInfo (CreateCorpusRequestModel body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RagcorporaApi->CreateACorpusV3RagCorporaPost");

            var localVarPath = "/v3/rag/corpora";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateACorpusV3RagCorporaPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateCorpusResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateCorpusResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateCorpusResponseModel)));
        }

        /// <summary>
        /// Create A Corpus Creates a corpus.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of CreateCorpusResponseModel</returns>
        public async System.Threading.Tasks.Task<CreateCorpusResponseModel> CreateACorpusV3RagCorporaPostAsync (CreateCorpusRequestModel body)
        {
             ApiResponse<CreateCorpusResponseModel> localVarResponse = await CreateACorpusV3RagCorporaPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A Corpus Creates a corpus.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <returns>Task of ApiResponse (CreateCorpusResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateCorpusResponseModel>> CreateACorpusV3RagCorporaPostAsyncWithHttpInfo (CreateCorpusRequestModel body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RagcorporaApi->CreateACorpusV3RagCorporaPost");

            var localVarPath = "/v3/rag/corpora";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateACorpusV3RagCorporaPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateCorpusResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateCorpusResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateCorpusResponseModel)));
        }

        /// <summary>
        /// Delete A Corpus Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Object</returns>
        public Object DeleteACorpusV3RagCorporaCorpusIdDelete (Object corpusId)
        {
             ApiResponse<Object> localVarResponse = DeleteACorpusV3RagCorporaCorpusIdDeleteWithHttpInfo(corpusId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete A Corpus Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse< Object > DeleteACorpusV3RagCorporaCorpusIdDeleteWithHttpInfo (Object corpusId)
        {
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->DeleteACorpusV3RagCorporaCorpusIdDelete");

            var localVarPath = "/v3/rag/corpora/{corpus_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteACorpusV3RagCorporaCorpusIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Delete A Corpus Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DeleteACorpusV3RagCorporaCorpusIdDeleteAsync (Object corpusId)
        {
             ApiResponse<Object> localVarResponse = await DeleteACorpusV3RagCorporaCorpusIdDeleteAsyncWithHttpInfo(corpusId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete A Corpus Deletes the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> DeleteACorpusV3RagCorporaCorpusIdDeleteAsyncWithHttpInfo (Object corpusId)
        {
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->DeleteACorpusV3RagCorporaCorpusIdDelete");

            var localVarPath = "/v3/rag/corpora/{corpus_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Delete, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteACorpusV3RagCorporaCorpusIdDelete", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Object) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Object)));
        }

        /// <summary>
        /// Get A Corpus Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>GetCorpusResponseModel</returns>
        public GetCorpusResponseModel GetACorpusV3RagCorporaCorpusIdGet (Object corpusId)
        {
             ApiResponse<GetCorpusResponseModel> localVarResponse = GetACorpusV3RagCorporaCorpusIdGetWithHttpInfo(corpusId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get A Corpus Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of GetCorpusResponseModel</returns>
        public ApiResponse< GetCorpusResponseModel > GetACorpusV3RagCorporaCorpusIdGetWithHttpInfo (Object corpusId)
        {
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->GetACorpusV3RagCorporaCorpusIdGet");

            var localVarPath = "/v3/rag/corpora/{corpus_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetACorpusV3RagCorporaCorpusIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetCorpusResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetCorpusResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetCorpusResponseModel)));
        }

        /// <summary>
        /// Get A Corpus Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of GetCorpusResponseModel</returns>
        public async System.Threading.Tasks.Task<GetCorpusResponseModel> GetACorpusV3RagCorporaCorpusIdGetAsync (Object corpusId)
        {
             ApiResponse<GetCorpusResponseModel> localVarResponse = await GetACorpusV3RagCorporaCorpusIdGetAsyncWithHttpInfo(corpusId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get A Corpus Returns a corpus matching the provided &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (GetCorpusResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GetCorpusResponseModel>> GetACorpusV3RagCorporaCorpusIdGetAsyncWithHttpInfo (Object corpusId)
        {
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->GetACorpusV3RagCorporaCorpusIdGet");

            var localVarPath = "/v3/rag/corpora/{corpus_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetACorpusV3RagCorporaCorpusIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GetCorpusResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (GetCorpusResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(GetCorpusResponseModel)));
        }

        /// <summary>
        /// List All Corpora Lists all corpora.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListCorporaResponseModel</returns>
        public ListCorporaResponseModel ListAllCorporaV3RagCorporaGet ()
        {
             ApiResponse<ListCorporaResponseModel> localVarResponse = ListAllCorporaV3RagCorporaGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// List All Corpora Lists all corpora.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListCorporaResponseModel</returns>
        public ApiResponse< ListCorporaResponseModel > ListAllCorporaV3RagCorporaGetWithHttpInfo ()
        {

            var localVarPath = "/v3/rag/corpora";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAllCorporaV3RagCorporaGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListCorporaResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListCorporaResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListCorporaResponseModel)));
        }

        /// <summary>
        /// List All Corpora Lists all corpora.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ListCorporaResponseModel</returns>
        public async System.Threading.Tasks.Task<ListCorporaResponseModel> ListAllCorporaV3RagCorporaGetAsync ()
        {
             ApiResponse<ListCorporaResponseModel> localVarResponse = await ListAllCorporaV3RagCorporaGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// List All Corpora Lists all corpora.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (ListCorporaResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListCorporaResponseModel>> ListAllCorporaV3RagCorporaGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/v3/rag/corpora";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListAllCorporaV3RagCorporaGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListCorporaResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListCorporaResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListCorporaResponseModel)));
        }

        /// <summary>
        /// List Corpus Reference Objects Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ListCorpusReferenceObjectsResponseModel</returns>
        public ListCorpusReferenceObjectsResponseModel ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet (Object corpusId)
        {
             ApiResponse<ListCorpusReferenceObjectsResponseModel> localVarResponse = ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetWithHttpInfo(corpusId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List Corpus Reference Objects Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of ListCorpusReferenceObjectsResponseModel</returns>
        public ApiResponse< ListCorpusReferenceObjectsResponseModel > ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetWithHttpInfo (Object corpusId)
        {
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet");

            var localVarPath = "/v3/rag/corpora/{corpus_id}/reference_objects";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListCorpusReferenceObjectsResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListCorpusReferenceObjectsResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListCorpusReferenceObjectsResponseModel)));
        }

        /// <summary>
        /// List Corpus Reference Objects Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ListCorpusReferenceObjectsResponseModel</returns>
        public async System.Threading.Tasks.Task<ListCorpusReferenceObjectsResponseModel> ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetAsync (Object corpusId)
        {
             ApiResponse<ListCorpusReferenceObjectsResponseModel> localVarResponse = await ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetAsyncWithHttpInfo(corpusId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List Corpus Reference Objects Lists all reference objects associated with a corpus specified in &#x60;organization_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (ListCorpusReferenceObjectsResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ListCorpusReferenceObjectsResponseModel>> ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGetAsyncWithHttpInfo (Object corpusId)
        {
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet");

            var localVarPath = "/v3/rag/corpora/{corpus_id}/reference_objects";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ListCorpusReferenceObjectsV3RagCorporaCorpusIdReferenceObjectsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ListCorpusReferenceObjectsResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ListCorpusReferenceObjectsResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ListCorpusReferenceObjectsResponseModel)));
        }

        /// <summary>
        /// Update A Corpus Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>UpdateCorpusResponseModel</returns>
        public UpdateCorpusResponseModel UpdateACorpusV3RagCorporaCorpusIdPatch (UpdateCorpusRequestModel body, Object corpusId)
        {
             ApiResponse<UpdateCorpusResponseModel> localVarResponse = UpdateACorpusV3RagCorporaCorpusIdPatchWithHttpInfo(body, corpusId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update A Corpus Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>ApiResponse of UpdateCorpusResponseModel</returns>
        public ApiResponse< UpdateCorpusResponseModel > UpdateACorpusV3RagCorporaCorpusIdPatchWithHttpInfo (UpdateCorpusRequestModel body, Object corpusId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RagcorporaApi->UpdateACorpusV3RagCorporaCorpusIdPatch");
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->UpdateACorpusV3RagCorporaCorpusIdPatch");

            var localVarPath = "/v3/rag/corpora/{corpus_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Patch, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateACorpusV3RagCorporaCorpusIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UpdateCorpusResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (UpdateCorpusResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(UpdateCorpusResponseModel)));
        }

        /// <summary>
        /// Update A Corpus Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>Task of UpdateCorpusResponseModel</returns>
        public async System.Threading.Tasks.Task<UpdateCorpusResponseModel> UpdateACorpusV3RagCorporaCorpusIdPatchAsync (UpdateCorpusRequestModel body, Object corpusId)
        {
             ApiResponse<UpdateCorpusResponseModel> localVarResponse = await UpdateACorpusV3RagCorporaCorpusIdPatchAsyncWithHttpInfo(body, corpusId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update A Corpus Updates the corpus specified in &#x60;corpus_id&#x60;.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"></param>
        /// <returns>Task of ApiResponse (UpdateCorpusResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<UpdateCorpusResponseModel>> UpdateACorpusV3RagCorporaCorpusIdPatchAsyncWithHttpInfo (UpdateCorpusRequestModel body, Object corpusId)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RagcorporaApi->UpdateACorpusV3RagCorporaCorpusIdPatch");
            // verify the required parameter 'corpusId' is set
            if (corpusId == null)
                throw new ApiException(400, "Missing required parameter 'corpusId' when calling RagcorporaApi->UpdateACorpusV3RagCorporaCorpusIdPatch");

            var localVarPath = "/v3/rag/corpora/{corpus_id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarPathParams.Add("corpus_id", this.Configuration.ApiClient.ParameterToString(corpusId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Patch, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateACorpusV3RagCorporaCorpusIdPatch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<UpdateCorpusResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (UpdateCorpusResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(UpdateCorpusResponseModel)));
        }

    }
}
