/* 
 * Kenja AI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0.0b1
 * Contact: info@kenja.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IRagsearchesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create A Reference Object Search
        /// </summary>
        /// <remarks>
        /// Creates a reference object search query and returns results.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>CreateReferenceObjectSearchResponseModel</returns>
        CreateReferenceObjectSearchResponseModel CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost (CreateReferenceObjectSearchRequestModel body, Object corpusId = null);

        /// <summary>
        /// Create A Reference Object Search
        /// </summary>
        /// <remarks>
        /// Creates a reference object search query and returns results.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>ApiResponse of CreateReferenceObjectSearchResponseModel</returns>
        ApiResponse<CreateReferenceObjectSearchResponseModel> CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostWithHttpInfo (CreateReferenceObjectSearchRequestModel body, Object corpusId = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create A Reference Object Search
        /// </summary>
        /// <remarks>
        /// Creates a reference object search query and returns results.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>Task of CreateReferenceObjectSearchResponseModel</returns>
        System.Threading.Tasks.Task<CreateReferenceObjectSearchResponseModel> CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostAsync (CreateReferenceObjectSearchRequestModel body, Object corpusId = null);

        /// <summary>
        /// Create A Reference Object Search
        /// </summary>
        /// <remarks>
        /// Creates a reference object search query and returns results.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>Task of ApiResponse (CreateReferenceObjectSearchResponseModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateReferenceObjectSearchResponseModel>> CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostAsyncWithHttpInfo (CreateReferenceObjectSearchRequestModel body, Object corpusId = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class RagsearchesApi : IRagsearchesApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RagsearchesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RagsearchesApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RagsearchesApi"/> class
        /// </summary>
        /// <returns></returns>
        public RagsearchesApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RagsearchesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RagsearchesApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create A Reference Object Search Creates a reference object search query and returns results.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>CreateReferenceObjectSearchResponseModel</returns>
        public CreateReferenceObjectSearchResponseModel CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost (CreateReferenceObjectSearchRequestModel body, Object corpusId = null)
        {
             ApiResponse<CreateReferenceObjectSearchResponseModel> localVarResponse = CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostWithHttpInfo(body, corpusId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create A Reference Object Search Creates a reference object search query and returns results.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>ApiResponse of CreateReferenceObjectSearchResponseModel</returns>
        public ApiResponse< CreateReferenceObjectSearchResponseModel > CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostWithHttpInfo (CreateReferenceObjectSearchRequestModel body, Object corpusId = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RagsearchesApi->CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost");

            var localVarPath = "/v3/rag/searches/reference_objects";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "corpus_id", corpusId)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateReferenceObjectSearchResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateReferenceObjectSearchResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateReferenceObjectSearchResponseModel)));
        }

        /// <summary>
        /// Create A Reference Object Search Creates a reference object search query and returns results.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>Task of CreateReferenceObjectSearchResponseModel</returns>
        public async System.Threading.Tasks.Task<CreateReferenceObjectSearchResponseModel> CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostAsync (CreateReferenceObjectSearchRequestModel body, Object corpusId = null)
        {
             ApiResponse<CreateReferenceObjectSearchResponseModel> localVarResponse = await CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostAsyncWithHttpInfo(body, corpusId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create A Reference Object Search Creates a reference object search query and returns results.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"></param>
        /// <param name="corpusId"> (optional)</param>
        /// <returns>Task of ApiResponse (CreateReferenceObjectSearchResponseModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CreateReferenceObjectSearchResponseModel>> CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPostAsyncWithHttpInfo (CreateReferenceObjectSearchRequestModel body, Object corpusId = null)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling RagsearchesApi->CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost");

            var localVarPath = "/v3/rag/searches/reference_objects";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (corpusId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "corpus_id", corpusId)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }
            // authentication (BearerAuth) required
            // bearer required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            RestResponse localVarResponse = (RestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.Post, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CreateAReferenceObjectSearchV3RagSearchesReferenceObjectsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CreateReferenceObjectSearchResponseModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (CreateReferenceObjectSearchResponseModel) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(CreateReferenceObjectSearchResponseModel)));
        }

    }
}
